<?php

// Data functions (insert, update, delete, form) for table all_bank_account_statement_table

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function all_bank_account_statement_table_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('all_bank_account_statement_table');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'statement_type' => Request::val('statement_type', ''),
		'txn_date' => Request::dateComponents('txn_date', '1'),
		'value_date' => Request::dateComponents('value_date', '1'),
		'description' => br2nl(Request::val('description', '')),
		'ref_no_or_cheque_no' => Request::val('ref_no_or_cheque_no', ''),
		'branch_code' => Request::val('branch_code', ''),
		'debit' => Request::val('debit', ''),
		'credit' => Request::val('credit', ''),
		'balance_1' => Request::val('balance_1', ''),
		'balance_2' => Request::val('balance_2', ''),
		'remarks_1' => br2nl(Request::val('remarks_1', '')),
		'remarks_2' => Request::val('remarks_2', ''),
		'category' => Request::val('category', ''),
		'created_by' => parseCode('<%%creatorUsername%%>', true),
		'created_at' => parseCode('<%%creationDateTime%%>', true),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('all_bank_account_statement_table', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		all_bank_account_statement_table_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function all_bank_account_statement_table_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function all_bank_account_statement_table_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('all_bank_account_statement_table', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: all_bank_account_statement_table_before_delete
	if(function_exists('all_bank_account_statement_table_before_delete')) {
		$args = [];
		if(!all_bank_account_statement_table_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: ''
			);
	}

	sql("DELETE FROM `all_bank_account_statement_table` WHERE `all_bank_account_statement_id`='{$selected_id}'", $eo);

	// hook: all_bank_account_statement_table_after_delete
	if(function_exists('all_bank_account_statement_table_after_delete')) {
		$args = [];
		all_bank_account_statement_table_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='all_bank_account_statement_table' AND `pkValue`='{$selected_id}'", $eo);
}

function all_bank_account_statement_table_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('all_bank_account_statement_table', $selected_id, 'edit')) return false;

	$data = [
		'statement_type' => Request::val('statement_type', ''),
		'txn_date' => Request::dateComponents('txn_date', ''),
		'value_date' => Request::dateComponents('value_date', ''),
		'description' => br2nl(Request::val('description', '')),
		'ref_no_or_cheque_no' => Request::val('ref_no_or_cheque_no', ''),
		'branch_code' => Request::val('branch_code', ''),
		'debit' => Request::val('debit', ''),
		'credit' => Request::val('credit', ''),
		'balance_1' => Request::val('balance_1', ''),
		'balance_2' => Request::val('balance_2', ''),
		'remarks_1' => br2nl(Request::val('remarks_1', '')),
		'remarks_2' => Request::val('remarks_2', ''),
		'category' => Request::val('category', ''),
		'last_updated_by' => parseCode('<%%editorUsername%%>', false),
		'last_updated_at' => parseCode('<%%editingDateTime%%>', false),
	];

	// get existing values
	$old_data = getRecord('all_bank_account_statement_table', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: all_bank_account_statement_table_before_update
	if(function_exists('all_bank_account_statement_table_before_update')) {
		$args = ['old_data' => $old_data];
		if(!all_bank_account_statement_table_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'all_bank_account_statement_table',
		backtick_keys_once($set),
		['`all_bank_account_statement_id`' => $selected_id],
		$error_message
	)) {
		echo $error_message;
		echo '<a href="all_bank_account_statement_table_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	update_calc_fields('all_bank_account_statement_table', $data['selectedID'], calculated_fields()['all_bank_account_statement_table']);

	// hook: all_bank_account_statement_table_after_update
	if(function_exists('all_bank_account_statement_table_after_update')) {
		if($row = getRecord('all_bank_account_statement_table', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['all_bank_account_statement_id'];
		$args = ['old_data' => $old_data];
		if(!all_bank_account_statement_table_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('all_bank_account_statement_table', $selected_id);
}

function all_bank_account_statement_table_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = true;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('all_bank_account_statement_table');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('all_bank_account_statement_table', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('all_bank_account_statement_table', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('all_bank_account_statement_table', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: statement_type
	$combo_statement_type = new Combo;
	$combo_statement_type->ListType = 0;
	$combo_statement_type->MultipleSeparator = ', ';
	$combo_statement_type->ListBoxHeight = 10;
	$combo_statement_type->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/all_bank_account_statement_table.statement_type.csv')) {
		$statement_type_data = addslashes(implode('', @file(__DIR__ . '/hooks/all_bank_account_statement_table.statement_type.csv')));
		$combo_statement_type->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($statement_type_data))));
		$combo_statement_type->ListData = $combo_statement_type->ListItem;
	} else {
		$combo_statement_type->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("DONATIONS;;OGC;;CONFERENCE;;CSR;;MAIN"))));
		$combo_statement_type->ListData = $combo_statement_type->ListItem;
	}
	$combo_statement_type->SelectName = 'statement_type';
	// combobox: txn_date
	$combo_txn_date = new DateCombo;
	$combo_txn_date->DateFormat = "dmy";
	$combo_txn_date->MinYear = defined('all_bank_account_statement_table.txn_date.MinYear') ? constant('all_bank_account_statement_table.txn_date.MinYear') : 1900;
	$combo_txn_date->MaxYear = defined('all_bank_account_statement_table.txn_date.MaxYear') ? constant('all_bank_account_statement_table.txn_date.MaxYear') : 2100;
	$combo_txn_date->DefaultDate = parseMySQLDate('1', '1');
	$combo_txn_date->MonthNames = $Translation['month names'];
	$combo_txn_date->NamePrefix = 'txn_date';
	// combobox: value_date
	$combo_value_date = new DateCombo;
	$combo_value_date->DateFormat = "dmy";
	$combo_value_date->MinYear = defined('all_bank_account_statement_table.value_date.MinYear') ? constant('all_bank_account_statement_table.value_date.MinYear') : 1900;
	$combo_value_date->MaxYear = defined('all_bank_account_statement_table.value_date.MaxYear') ? constant('all_bank_account_statement_table.value_date.MaxYear') : 2100;
	$combo_value_date->DefaultDate = parseMySQLDate('1', '1');
	$combo_value_date->MonthNames = $Translation['month names'];
	$combo_value_date->NamePrefix = 'value_date';

	if($hasSelectedId) {
		if(!($row = getRecord('all_bank_account_statement_table', $selectedId))) {
			return error_message($Translation['No records found'], 'all_bank_account_statement_table_view.php', false);
		}
		$combo_statement_type->SelectedData = $row['statement_type'];
		$combo_txn_date->DefaultDate = $row['txn_date'];
		$combo_value_date->DefaultDate = $row['value_date'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_statement_type->SelectedText = (isset($filterField[1]) && $filterField[1] == '2' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
	}
	$combo_statement_type->Render();

	ob_start();
	?>

	<script>
		// initial lookup values

		$j(function() {
			setTimeout(function() {
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/all_bank_account_statement_table_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/all_bank_account_statement_table_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'All bank account statement table details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default ltr" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>',
				'<button
					type="submit"
					class="btn btn-default ltr"
					id="deselect"
					name="deselect_x"
					value="1"
					onclick="' . $backAction . '"
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#statement_type').replaceWith('<div class=\"form-control-static\" id=\"statement_type\">' + (\$j('#statement_type').val() || '') + '</div>'); \$j('#statement_type-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#txn_date').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#txn_dateDay, #txn_dateMonth, #txn_dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#value_date').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#value_dateDay, #value_dateMonth, #value_dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#description').replaceWith('<div class=\"form-control-static\" id=\"description\">' + (\$j('#description').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#ref_no_or_cheque_no').replaceWith('<div class=\"form-control-static\" id=\"ref_no_or_cheque_no\">' + (\$j('#ref_no_or_cheque_no').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#branch_code').replaceWith('<div class=\"form-control-static\" id=\"branch_code\">' + (\$j('#branch_code').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#debit').replaceWith('<div class=\"form-control-static\" id=\"debit\">' + (\$j('#debit').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#credit').replaceWith('<div class=\"form-control-static\" id=\"credit\">' + (\$j('#credit').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#balance_1').replaceWith('<div class=\"form-control-static\" id=\"balance_1\">' + (\$j('#balance_1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#balance_2').replaceWith('<div class=\"form-control-static\" id=\"balance_2\">' + (\$j('#balance_2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#remarks_1').replaceWith('<div class=\"form-control-static\" id=\"remarks_1\">' + (\$j('#remarks_1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#remarks_2').replaceWith('<div class=\"form-control-static\" id=\"remarks_2\">' + (\$j('#remarks_2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#category').replaceWith('<div class=\"form-control-static\" id=\"category\">' + (\$j('#category').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(statement_type)%%>', $combo_statement_type->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(statement_type)%%>', $combo_statement_type->SelectedData, $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(txn_date)%%>',
		(!$fieldsAreEditable ?
			'<div class="form-control-static">' . $combo_txn_date->GetHTML(true) . '</div>' :
			$combo_txn_date->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(txn_date)%%>', $combo_txn_date->GetHTML(true), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(value_date)%%>',
		(!$fieldsAreEditable ?
			'<div class="form-control-static">' . $combo_value_date->GetHTML(true) . '</div>' :
			$combo_value_date->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(value_date)%%>', $combo_value_date->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = [];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(all_bank_account_statement_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(statement_type)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(txn_date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(value_date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(description)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ref_no_or_cheque_no)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(branch_code)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(debit)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(credit)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(balance_1)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(balance_2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(remarks_1)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(remarks_2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(category)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_at)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_at)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_by_username)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_by_username)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		$templateCode = str_replace('<%%VALUE(all_bank_account_statement_id)%%>', safe_html($urow['all_bank_account_statement_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(all_bank_account_statement_id)%%>', urlencode($urow['all_bank_account_statement_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(statement_type)%%>', safe_html($urow['statement_type']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(statement_type)%%>', html_attr($row['statement_type']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(statement_type)%%>', urlencode($urow['statement_type']), $templateCode);
		$templateCode = str_replace('<%%VALUE(txn_date)%%>', app_datetime($row['txn_date']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(txn_date)%%>', urlencode(app_datetime($urow['txn_date'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(value_date)%%>', app_datetime($row['value_date']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(value_date)%%>', urlencode(app_datetime($urow['value_date'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(description)%%>', safe_html($urow['description'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(description)%%>', urlencode($urow['description']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ref_no_or_cheque_no)%%>', safe_html($urow['ref_no_or_cheque_no']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ref_no_or_cheque_no)%%>', html_attr($row['ref_no_or_cheque_no']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ref_no_or_cheque_no)%%>', urlencode($urow['ref_no_or_cheque_no']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(branch_code)%%>', safe_html($urow['branch_code']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(branch_code)%%>', html_attr($row['branch_code']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(branch_code)%%>', urlencode($urow['branch_code']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(debit)%%>', safe_html($urow['debit']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(debit)%%>', html_attr($row['debit']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(debit)%%>', urlencode($urow['debit']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(credit)%%>', safe_html($urow['credit']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(credit)%%>', html_attr($row['credit']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(credit)%%>', urlencode($urow['credit']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(balance_1)%%>', safe_html($urow['balance_1']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(balance_1)%%>', html_attr($row['balance_1']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(balance_1)%%>', urlencode($urow['balance_1']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(balance_2)%%>', safe_html($urow['balance_2']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(balance_2)%%>', html_attr($row['balance_2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(balance_2)%%>', urlencode($urow['balance_2']), $templateCode);
		$templateCode = str_replace('<%%VALUE(remarks_1)%%>', safe_html($urow['remarks_1'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(remarks_1)%%>', urlencode($urow['remarks_1']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(remarks_2)%%>', safe_html($urow['remarks_2']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(remarks_2)%%>', html_attr($row['remarks_2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(remarks_2)%%>', urlencode($urow['remarks_2']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(category)%%>', safe_html($urow['category']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(category)%%>', html_attr($row['category']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(category)%%>', urlencode($urow['category']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', safe_html($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_at)%%>', safe_html($urow['created_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode($urow['created_at']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by)%%>', safe_html($urow['last_updated_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by)%%>', urlencode($urow['last_updated_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_at)%%>', safe_html($urow['last_updated_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_at)%%>', urlencode($urow['last_updated_at']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by_username)%%>', safe_html($urow['created_by_username']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by_username)%%>', urlencode($urow['created_by_username']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by_username)%%>', safe_html($urow['last_updated_by_username']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by_username)%%>', urlencode($urow['last_updated_by_username']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(all_bank_account_statement_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(all_bank_account_statement_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(statement_type)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(statement_type)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(txn_date)%%>', '1', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(txn_date)%%>', urlencode('1'), $templateCode);
		$templateCode = str_replace('<%%VALUE(value_date)%%>', '1', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(value_date)%%>', urlencode('1'), $templateCode);
		$templateCode = str_replace('<%%VALUE(description)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(description)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ref_no_or_cheque_no)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ref_no_or_cheque_no)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(branch_code)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(branch_code)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(debit)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(debit)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(credit)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(credit)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(balance_1)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(balance_1)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(balance_2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(balance_2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(remarks_1)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(remarks_1)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(remarks_2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(remarks_2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(category)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(category)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_at)%%>', '<%%creationDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode('<%%creationDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by)%%>', '<%%editorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by)%%>', urlencode('<%%editorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_at)%%>', '<%%editingDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_at)%%>', urlencode('<%%editingDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by_username)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by_username)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by_username)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by_username)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('all_bank_account_statement_table');
	if($hasSelectedId) {
		$jdata = get_joined_record('all_bank_account_statement_table', $selectedId);
		if($jdata === false) $jdata = get_defaults('all_bank_account_statement_table');
		$rdata = $row;
	}
	$templateCode .= loadView('all_bank_account_statement_table-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: all_bank_account_statement_table_dv
	if(function_exists('all_bank_account_statement_table_dv')) {
		$args = [];
		all_bank_account_statement_table_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}