<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/asset_table.php');
	include_once(__DIR__ . '/asset_table_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('asset_table');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'asset_table';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`asset_table`.`id`" => "id",
		"`asset_table`.`username`" => "username",
		"if(`asset_table`.`Date`,date_format(`asset_table`.`Date`,'%d/%m/%Y'),'')" => "Date",
		"`asset_table`.`ClassificationofAssest`" => "ClassificationofAssest",
		"`asset_table`.`SubCategory`" => "SubCategory",
		"`asset_table`.`AssetSerialNo`" => "AssetSerialNo",
		"`asset_table`.`QRBarCode`" => "QRBarCode",
		"`asset_table`.`AssetNo`" => "AssetNo",
		"`asset_table`.`PONO`" => "PONO",
		"if(`asset_table`.`PODATE`,date_format(`asset_table`.`PODATE`,'%d/%m/%Y'),'')" => "PODATE",
		"`asset_table`.`particulars_of_supplier_name_address`" => "particulars_of_supplier_name_address",
		"`asset_table`.`ItemDescription`" => "ItemDescription",
		"`asset_table`.`BillNo`" => "BillNo",
		"if(`asset_table`.`BillDate`,date_format(`asset_table`.`BillDate`,'%d/%m/%Y'),'')" => "BillDate",
		"`asset_table`.`QUANTITY`" => "QUANTITY",
		"`asset_table`.`CostoftheAssetinINR`" => "CostoftheAssetinINR",
		"`asset_table`.`TotalInvoiceValueinINR`" => "TotalInvoiceValueinINR",
		"`asset_table`.`CustodyDepartment`" => "CustodyDepartment",
		"`asset_table`.`custodian`" => "custodian",
		"`asset_table`.`CustodianSignature`" => "CustodianSignature",
		"`asset_table`.`remarks`" => "remarks",
		"`asset_table`.`last_updated_by`" => "last_updated_by",
		"`asset_table`.`last_updated_at`" => "last_updated_at",
		"`asset_table`.`created_by`" => "created_by",
		"`asset_table`.`created_by_username`" => "created_by_username",
		"`asset_table`.`created_at`" => "created_at",
		"`asset_table`.`last_updated_by_username`" => "last_updated_by_username",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`asset_table`.`id`',
		2 => 2,
		3 => '`asset_table`.`Date`',
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => '`asset_table`.`PODATE`',
		11 => 11,
		12 => 12,
		13 => 13,
		14 => '`asset_table`.`BillDate`',
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19,
		20 => 20,
		21 => 21,
		22 => 22,
		23 => 23,
		24 => 24,
		25 => 25,
		26 => 26,
		27 => 27,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`asset_table`.`id`" => "id",
		"`asset_table`.`username`" => "username",
		"if(`asset_table`.`Date`,date_format(`asset_table`.`Date`,'%d/%m/%Y'),'')" => "Date",
		"`asset_table`.`ClassificationofAssest`" => "ClassificationofAssest",
		"`asset_table`.`SubCategory`" => "SubCategory",
		"`asset_table`.`AssetSerialNo`" => "AssetSerialNo",
		"`asset_table`.`QRBarCode`" => "QRBarCode",
		"`asset_table`.`AssetNo`" => "AssetNo",
		"`asset_table`.`PONO`" => "PONO",
		"if(`asset_table`.`PODATE`,date_format(`asset_table`.`PODATE`,'%d/%m/%Y'),'')" => "PODATE",
		"`asset_table`.`particulars_of_supplier_name_address`" => "particulars_of_supplier_name_address",
		"`asset_table`.`ItemDescription`" => "ItemDescription",
		"`asset_table`.`BillNo`" => "BillNo",
		"if(`asset_table`.`BillDate`,date_format(`asset_table`.`BillDate`,'%d/%m/%Y'),'')" => "BillDate",
		"`asset_table`.`QUANTITY`" => "QUANTITY",
		"`asset_table`.`CostoftheAssetinINR`" => "CostoftheAssetinINR",
		"`asset_table`.`TotalInvoiceValueinINR`" => "TotalInvoiceValueinINR",
		"`asset_table`.`CustodyDepartment`" => "CustodyDepartment",
		"`asset_table`.`custodian`" => "custodian",
		"`asset_table`.`CustodianSignature`" => "CustodianSignature",
		"`asset_table`.`remarks`" => "remarks",
		"`asset_table`.`last_updated_by`" => "last_updated_by",
		"`asset_table`.`last_updated_at`" => "last_updated_at",
		"`asset_table`.`created_by`" => "created_by",
		"`asset_table`.`created_by_username`" => "created_by_username",
		"`asset_table`.`created_at`" => "created_at",
		"`asset_table`.`last_updated_by_username`" => "last_updated_by_username",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`asset_table`.`id`" => "ID",
		"`asset_table`.`username`" => "Username",
		"`asset_table`.`Date`" => "Date",
		"`asset_table`.`ClassificationofAssest`" => "Classification of Assest",
		"`asset_table`.`SubCategory`" => "Sub Category",
		"`asset_table`.`AssetSerialNo`" => "Asset Serial No",
		"`asset_table`.`QRBarCode`" => "QR & Bar Code",
		"`asset_table`.`AssetNo`" => "Asset No",
		"`asset_table`.`PONO`" => "PO. NO.",
		"`asset_table`.`PODATE`" => "P/O Date",
		"`asset_table`.`particulars_of_supplier_name_address`" => "Partculars of Supplier Vendor Name & Address",
		"`asset_table`.`ItemDescription`" => "Item Description",
		"`asset_table`.`BillNo`" => "Bill No.",
		"`asset_table`.`BillDate`" => "Bill Date",
		"`asset_table`.`QUANTITY`" => "Quantity",
		"`asset_table`.`CostoftheAssetinINR`" => "Cost of the Asset (in INR)",
		"`asset_table`.`TotalInvoiceValueinINR`" => "Total Invoice Value (in INR)",
		"`asset_table`.`CustodyDepartment`" => "Custody Department",
		"`asset_table`.`custodian`" => "Custodian",
		"`asset_table`.`CustodianSignature`" => "Custodian Signature",
		"`asset_table`.`remarks`" => "Remarks",
		"`asset_table`.`last_updated_by`" => "Last updated by",
		"`asset_table`.`last_updated_at`" => "Last updated at",
		"`asset_table`.`created_by`" => "Created By",
		"`asset_table`.`created_by_username`" => "Created By Username",
		"`asset_table`.`created_at`" => "Created At",
		"`asset_table`.`last_updated_by_username`" => "Last Updated by Username",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`asset_table`.`id`" => "id",
		"`asset_table`.`username`" => "username",
		"if(`asset_table`.`Date`,date_format(`asset_table`.`Date`,'%d/%m/%Y'),'')" => "Date",
		"`asset_table`.`ClassificationofAssest`" => "ClassificationofAssest",
		"`asset_table`.`SubCategory`" => "SubCategory",
		"`asset_table`.`AssetSerialNo`" => "AssetSerialNo",
		"`asset_table`.`QRBarCode`" => "QRBarCode",
		"`asset_table`.`AssetNo`" => "AssetNo",
		"`asset_table`.`PONO`" => "PONO",
		"if(`asset_table`.`PODATE`,date_format(`asset_table`.`PODATE`,'%d/%m/%Y'),'')" => "PODATE",
		"`asset_table`.`particulars_of_supplier_name_address`" => "particulars_of_supplier_name_address",
		"`asset_table`.`ItemDescription`" => "ItemDescription",
		"`asset_table`.`BillNo`" => "BillNo",
		"if(`asset_table`.`BillDate`,date_format(`asset_table`.`BillDate`,'%d/%m/%Y'),'')" => "BillDate",
		"`asset_table`.`QUANTITY`" => "QUANTITY",
		"`asset_table`.`CostoftheAssetinINR`" => "CostoftheAssetinINR",
		"`asset_table`.`TotalInvoiceValueinINR`" => "TotalInvoiceValueinINR",
		"`asset_table`.`CustodyDepartment`" => "CustodyDepartment",
		"`asset_table`.`custodian`" => "custodian",
		"`asset_table`.`CustodianSignature`" => "CustodianSignature",
		"`asset_table`.`remarks`" => "remarks",
		"`asset_table`.`last_updated_by`" => "last_updated_by",
		"`asset_table`.`last_updated_at`" => "last_updated_at",
		"`asset_table`.`created_by`" => "created_by",
		"`asset_table`.`created_by_username`" => "created_by_username",
		"`asset_table`.`created_at`" => "created_at",
		"`asset_table`.`last_updated_by_username`" => "last_updated_by_username",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`asset_table` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'asset_table_view.php';
	$x->TableTitle = 'Master Inventory (Admin Department) - App';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`asset_table`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Date', 'Classification of Assest', 'Sub Category', 'Asset Serial No', 'QR & Bar Code', 'Asset No', 'PO. NO.', 'P/O Date', 'Partculars of Supplier Vendor Name & Address', 'Item Description', 'Bill No.', 'Bill Date', 'Quantity', 'Cost of the Asset (in INR)', 'Total Invoice Value (in INR)', 'Custody Department', 'Custodian', 'Custodian Signature', 'Remarks', 'Last updated by', 'Last updated at', 'Created By', 'Created By Username', 'Created At', 'Last Updated by Username', ];
	$x->ColFieldName = ['id', 'Date', 'ClassificationofAssest', 'SubCategory', 'AssetSerialNo', 'QRBarCode', 'AssetNo', 'PONO', 'PODATE', 'particulars_of_supplier_name_address', 'ItemDescription', 'BillNo', 'BillDate', 'QUANTITY', 'CostoftheAssetinINR', 'TotalInvoiceValueinINR', 'CustodyDepartment', 'custodian', 'CustodianSignature', 'remarks', 'last_updated_by', 'last_updated_at', 'created_by', 'created_by_username', 'created_at', 'last_updated_by_username', ];
	$x->ColNumber  = [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/asset_table_templateTV.html';
	$x->SelectedTemplate = 'templates/asset_table_templateTVS.html';
	$x->TemplateDV = 'templates/asset_table_templateDV.html';
	$x->TemplateDVP = 'templates/asset_table_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: asset_table_init
	$render = true;
	if(function_exists('asset_table_init')) {
		$args = [];
		$render = asset_table_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: asset_table_header
	$headerCode = '';
	if(function_exists('asset_table_header')) {
		$args = [];
		$headerCode = asset_table_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: asset_table_footer
	$footerCode = '';
	if(function_exists('asset_table_footer')) {
		$args = [];
		$footerCode = asset_table_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
