<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/beyond_working_hours_table.php');
	include_once(__DIR__ . '/beyond_working_hours_table_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('beyond_working_hours_table');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'beyond_working_hours_table';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`beyond_working_hours_table`.`id`" => "id",
		"`beyond_working_hours_table`.`approval_from`" => "approval_from",
		"`beyond_working_hours_table`.`days_remark`" => "days_remark",
		"if(`beyond_working_hours_table`.`start_datetime`,date_format(`beyond_working_hours_table`.`start_datetime`,'%d/%m/%Y %H:%i'),'')" => "start_datetime",
		"if(`beyond_working_hours_table`.`end_datetime`,date_format(`beyond_working_hours_table`.`end_datetime`,'%d/%m/%Y %H:%i'),'')" => "end_datetime",
		"`beyond_working_hours_table`.`reason_for_overtime`" => "reason_for_overtime",
		"`beyond_working_hours_table`.`details_of_work_done`" => "details_of_work_done",
		"`beyond_working_hours_table`.`number_of_hours`" => "number_of_hours",
		"`beyond_working_hours_table`.`approval_status`" => "approval_status",
		"`beyond_working_hours_table`.`approval_remarks`" => "approval_remarks",
		"`beyond_working_hours_table`.`created_by_username`" => "created_by_username",
		"`beyond_working_hours_table`.`created_by`" => "created_by",
		"`beyond_working_hours_table`.`created_at`" => "created_at",
		"`beyond_working_hours_table`.`last_updated_by_username`" => "last_updated_by_username",
		"`beyond_working_hours_table`.`last_updated_by`" => "last_updated_by",
		"`beyond_working_hours_table`.`last_updated_at`" => "last_updated_at",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`beyond_working_hours_table`.`id`',
		2 => 2,
		3 => 3,
		4 => '`beyond_working_hours_table`.`start_datetime`',
		5 => '`beyond_working_hours_table`.`end_datetime`',
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`beyond_working_hours_table`.`id`" => "id",
		"`beyond_working_hours_table`.`approval_from`" => "approval_from",
		"`beyond_working_hours_table`.`days_remark`" => "days_remark",
		"if(`beyond_working_hours_table`.`start_datetime`,date_format(`beyond_working_hours_table`.`start_datetime`,'%d/%m/%Y %H:%i'),'')" => "start_datetime",
		"if(`beyond_working_hours_table`.`end_datetime`,date_format(`beyond_working_hours_table`.`end_datetime`,'%d/%m/%Y %H:%i'),'')" => "end_datetime",
		"`beyond_working_hours_table`.`reason_for_overtime`" => "reason_for_overtime",
		"`beyond_working_hours_table`.`details_of_work_done`" => "details_of_work_done",
		"`beyond_working_hours_table`.`number_of_hours`" => "number_of_hours",
		"`beyond_working_hours_table`.`approval_status`" => "approval_status",
		"`beyond_working_hours_table`.`approval_remarks`" => "approval_remarks",
		"`beyond_working_hours_table`.`created_by_username`" => "created_by_username",
		"`beyond_working_hours_table`.`created_by`" => "created_by",
		"`beyond_working_hours_table`.`created_at`" => "created_at",
		"`beyond_working_hours_table`.`last_updated_by_username`" => "last_updated_by_username",
		"`beyond_working_hours_table`.`last_updated_by`" => "last_updated_by",
		"`beyond_working_hours_table`.`last_updated_at`" => "last_updated_at",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`beyond_working_hours_table`.`id`" => "ID",
		"`beyond_working_hours_table`.`approval_from`" => "Approval From",
		"`beyond_working_hours_table`.`days_remark`" => "Days Remark (Mention Day Names like SUN,MON,TUE,WED,THU,FRI,SAT) & Name of Holiday as in TIH Calendar",
		"`beyond_working_hours_table`.`start_datetime`" => "Start Date & Time",
		"`beyond_working_hours_table`.`end_datetime`" => "End Date & Time",
		"`beyond_working_hours_table`.`reason_for_overtime`" => "Reason for Overtime",
		"`beyond_working_hours_table`.`details_of_work_done`" => "Details of Work Planned/Done (Justify Why Beyond Working Hours was Necessary Indiacating Project Urgency or Orders of Superiors(Designation of Superior) )",
		"`beyond_working_hours_table`.`number_of_hours`" => "Number of Hours",
		"`beyond_working_hours_table`.`approval_status`" => "Approval Status",
		"`beyond_working_hours_table`.`approval_remarks`" => "Approval Remarks",
		"`beyond_working_hours_table`.`created_by_username`" => "Created by Username",
		"`beyond_working_hours_table`.`created_by`" => "Created by",
		"`beyond_working_hours_table`.`created_at`" => "Created at",
		"`beyond_working_hours_table`.`last_updated_by_username`" => "Last Updated By Username",
		"`beyond_working_hours_table`.`last_updated_by`" => "Last updated by",
		"`beyond_working_hours_table`.`last_updated_at`" => "Last updated at",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`beyond_working_hours_table`.`id`" => "id",
		"`beyond_working_hours_table`.`approval_from`" => "approval_from",
		"`beyond_working_hours_table`.`days_remark`" => "days_remark",
		"if(`beyond_working_hours_table`.`start_datetime`,date_format(`beyond_working_hours_table`.`start_datetime`,'%d/%m/%Y %H:%i'),'')" => "start_datetime",
		"if(`beyond_working_hours_table`.`end_datetime`,date_format(`beyond_working_hours_table`.`end_datetime`,'%d/%m/%Y %H:%i'),'')" => "end_datetime",
		"`beyond_working_hours_table`.`reason_for_overtime`" => "reason_for_overtime",
		"`beyond_working_hours_table`.`details_of_work_done`" => "details_of_work_done",
		"`beyond_working_hours_table`.`number_of_hours`" => "number_of_hours",
		"`beyond_working_hours_table`.`approval_status`" => "approval_status",
		"`beyond_working_hours_table`.`approval_remarks`" => "approval_remarks",
		"`beyond_working_hours_table`.`created_by_username`" => "created_by_username",
		"`beyond_working_hours_table`.`created_by`" => "created_by",
		"`beyond_working_hours_table`.`created_at`" => "created_at",
		"`beyond_working_hours_table`.`last_updated_by_username`" => "last_updated_by_username",
		"`beyond_working_hours_table`.`last_updated_by`" => "last_updated_by",
		"`beyond_working_hours_table`.`last_updated_at`" => "last_updated_at",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`beyond_working_hours_table` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'beyond_working_hours_table_view.php';
	$x->TableTitle = 'Beyond Working Hours Approval - App';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`beyond_working_hours_table`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Approval From', 'Days Remark (Mention Day Names like SUN,MON,TUE,WED,THU,FRI,SAT) & Name of Holiday as in TIH Calendar', 'Start Date & Time', 'End Date & Time', 'Reason for Overtime', 'Details of Work Planned/Done (Justify Why Beyond Working Hours was Necessary Indiacating Project Urgency or Orders of Superiors(Designation of Superior) )', 'Number of Hours', 'Approval Status', 'Approval Remarks', 'Created by Username', 'Created by', 'Created at', 'Last Updated By Username', 'Last updated by', 'Last updated at', ];
	$x->ColFieldName = ['id', 'approval_from', 'days_remark', 'start_datetime', 'end_datetime', 'reason_for_overtime', 'details_of_work_done', 'number_of_hours', 'approval_status', 'approval_remarks', 'created_by_username', 'created_by', 'created_at', 'last_updated_by_username', 'last_updated_by', 'last_updated_at', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/beyond_working_hours_table_templateTV.html';
	$x->SelectedTemplate = 'templates/beyond_working_hours_table_templateTVS.html';
	$x->TemplateDV = 'templates/beyond_working_hours_table_templateDV.html';
	$x->TemplateDVP = 'templates/beyond_working_hours_table_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: beyond_working_hours_table_init
	$render = true;
	if(function_exists('beyond_working_hours_table_init')) {
		$args = [];
		$render = beyond_working_hours_table_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: beyond_working_hours_table_header
	$headerCode = '';
	if(function_exists('beyond_working_hours_table_header')) {
		$args = [];
		$headerCode = beyond_working_hours_table_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: beyond_working_hours_table_footer
	$footerCode = '';
	if(function_exists('beyond_working_hours_table_footer')) {
		$args = [];
		$footerCode = beyond_working_hours_table_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
