<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/employees_appraisal_table.php');
	include_once(__DIR__ . '/employees_appraisal_table_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('employees_appraisal_table');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'employees_appraisal_table';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`employees_appraisal_table`.`id`" => "id",
		"`employees_appraisal_table`.`employee_details`" => "employee_details",
		"`employees_appraisal_table`.`department`" => "department",
		"`employees_appraisal_table`.`designation`" => "designation",
		"`employees_appraisal_table`.`date_of_joining`" => "date_of_joining",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`employees_appraisal_table`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`employees_appraisal_table`.`id`" => "id",
		"`employees_appraisal_table`.`employee_details`" => "employee_details",
		"`employees_appraisal_table`.`department`" => "department",
		"`employees_appraisal_table`.`designation`" => "designation",
		"`employees_appraisal_table`.`date_of_joining`" => "date_of_joining",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`employees_appraisal_table`.`id`" => "ID",
		"`employees_appraisal_table`.`employee_details`" => "Employee details",
		"`employees_appraisal_table`.`department`" => "Department / Section",
		"`employees_appraisal_table`.`designation`" => "Designation",
		"`employees_appraisal_table`.`date_of_joining`" => "Date of joining",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`employees_appraisal_table`.`id`" => "id",
		"`employees_appraisal_table`.`employee_details`" => "employee_details",
		"`employees_appraisal_table`.`department`" => "department",
		"`employees_appraisal_table`.`designation`" => "designation",
		"`employees_appraisal_table`.`date_of_joining`" => "date_of_joining",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`employees_appraisal_table` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'employees_appraisal_table_view.php';
	$x->TableTitle = 'Employees Appraisal  - App';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`employees_appraisal_table`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Employee details', 'Department / Section', 'Designation', 'Date of joining', ];
	$x->ColFieldName = ['id', 'employee_details', 'department', 'designation', 'date_of_joining', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/employees_appraisal_table_templateTV.html';
	$x->SelectedTemplate = 'templates/employees_appraisal_table_templateTVS.html';
	$x->TemplateDV = 'templates/employees_appraisal_table_templateDV.html';
	$x->TemplateDVP = 'templates/employees_appraisal_table_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: employees_appraisal_table_init
	$render = true;
	if(function_exists('employees_appraisal_table_init')) {
		$args = [];
		$render = employees_appraisal_table_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: employees_appraisal_table_header
	$headerCode = '';
	if(function_exists('employees_appraisal_table_header')) {
		$args = [];
		$headerCode = employees_appraisal_table_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: employees_appraisal_table_footer
	$footerCode = '';
	if(function_exists('employees_appraisal_table_footer')) {
		$args = [];
		$footerCode = employees_appraisal_table_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
