<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/goal_setting_table.php');
	include_once(__DIR__ . '/goal_setting_table_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('goal_setting_table');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'goal_setting_table';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`goal_setting_table`.`goal_id`" => "goal_id",
		"`goal_setting_table`.`goal_status`" => "goal_status",
		"`goal_setting_table`.`goal_description`" => "goal_description",
		"`goal_setting_table`.`goal_duration`" => "goal_duration",
		"if(`goal_setting_table`.`goal_set_date`,date_format(`goal_setting_table`.`goal_set_date`,'%d/%m/%Y'),'')" => "goal_set_date",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Supervisor name */" => "supervisor_name",
		"IF(    CHAR_LENGTH(`user_table2`.`memberID`) || CHAR_LENGTH(`user_table2`.`name`), CONCAT_WS('',   `user_table2`.`memberID`, '::', `user_table2`.`name`), '') /* Assigned to */" => "assigned_to",
		"`goal_setting_table`.`goal_setting_str`" => "goal_setting_str",
		"`goal_setting_table`.`created_by`" => "created_by",
		"`goal_setting_table`.`last_updated_by`" => "last_updated_by",
		"`goal_setting_table`.`created_by_username`" => "created_by_username",
		"`goal_setting_table`.`created_at`" => "created_at",
		"`goal_setting_table`.`last_updated_by_username`" => "last_updated_by_username",
		"`goal_setting_table`.`last_updated_at`" => "last_updated_at",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`goal_setting_table`.`goal_id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`goal_setting_table`.`goal_set_date`',
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`goal_setting_table`.`goal_id`" => "goal_id",
		"`goal_setting_table`.`goal_status`" => "goal_status",
		"`goal_setting_table`.`goal_description`" => "goal_description",
		"`goal_setting_table`.`goal_duration`" => "goal_duration",
		"if(`goal_setting_table`.`goal_set_date`,date_format(`goal_setting_table`.`goal_set_date`,'%d/%m/%Y'),'')" => "goal_set_date",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Supervisor name */" => "supervisor_name",
		"IF(    CHAR_LENGTH(`user_table2`.`memberID`) || CHAR_LENGTH(`user_table2`.`name`), CONCAT_WS('',   `user_table2`.`memberID`, '::', `user_table2`.`name`), '') /* Assigned to */" => "assigned_to",
		"`goal_setting_table`.`goal_setting_str`" => "goal_setting_str",
		"`goal_setting_table`.`created_by`" => "created_by",
		"`goal_setting_table`.`last_updated_by`" => "last_updated_by",
		"`goal_setting_table`.`created_by_username`" => "created_by_username",
		"`goal_setting_table`.`created_at`" => "created_at",
		"`goal_setting_table`.`last_updated_by_username`" => "last_updated_by_username",
		"`goal_setting_table`.`last_updated_at`" => "last_updated_at",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`goal_setting_table`.`goal_id`" => "ID",
		"`goal_setting_table`.`goal_status`" => "Goal status",
		"`goal_setting_table`.`goal_description`" => "Goal description",
		"`goal_setting_table`.`goal_duration`" => "Goal duration",
		"`goal_setting_table`.`goal_set_date`" => "Goal set date",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Supervisor name */" => "Supervisor name",
		"IF(    CHAR_LENGTH(`user_table2`.`memberID`) || CHAR_LENGTH(`user_table2`.`name`), CONCAT_WS('',   `user_table2`.`memberID`, '::', `user_table2`.`name`), '') /* Assigned to */" => "Assigned to",
		"`goal_setting_table`.`goal_setting_str`" => "Goal setting str",
		"`goal_setting_table`.`created_by`" => "Created By",
		"`goal_setting_table`.`last_updated_by`" => "Last Updated By",
		"`goal_setting_table`.`created_by_username`" => "Created By Username",
		"`goal_setting_table`.`created_at`" => "Created At",
		"`goal_setting_table`.`last_updated_by_username`" => "Last Updated by Username",
		"`goal_setting_table`.`last_updated_at`" => "Last Updated At",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`goal_setting_table`.`goal_id`" => "goal_id",
		"`goal_setting_table`.`goal_status`" => "goal_status",
		"`goal_setting_table`.`goal_description`" => "goal_description",
		"`goal_setting_table`.`goal_duration`" => "goal_duration",
		"if(`goal_setting_table`.`goal_set_date`,date_format(`goal_setting_table`.`goal_set_date`,'%d/%m/%Y'),'')" => "goal_set_date",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Supervisor name */" => "supervisor_name",
		"IF(    CHAR_LENGTH(`user_table2`.`memberID`) || CHAR_LENGTH(`user_table2`.`name`), CONCAT_WS('',   `user_table2`.`memberID`, '::', `user_table2`.`name`), '') /* Assigned to */" => "assigned_to",
		"`goal_setting_table`.`goal_setting_str`" => "goal_setting_str",
		"`goal_setting_table`.`created_by`" => "created_by",
		"`goal_setting_table`.`last_updated_by`" => "last_updated_by",
		"`goal_setting_table`.`created_by_username`" => "created_by_username",
		"`goal_setting_table`.`created_at`" => "created_at",
		"`goal_setting_table`.`last_updated_by_username`" => "last_updated_by_username",
		"`goal_setting_table`.`last_updated_at`" => "last_updated_at",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['supervisor_name' => 'Supervisor name', 'assigned_to' => 'Assigned to', ];

	$x->QueryFrom = "`goal_setting_table` LEFT JOIN `user_table` as user_table1 ON `user_table1`.`user_id`=`goal_setting_table`.`supervisor_name` LEFT JOIN `user_table` as user_table2 ON `user_table2`.`user_id`=`goal_setting_table`.`assigned_to` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'goal_setting_table_view.php';
	$x->TableTitle = 'Goal setting - App';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`goal_setting_table`.`goal_id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Goal status', 'Goal description', 'Goal duration', 'Goal set date', 'Supervisor name', 'Assigned to', 'Goal setting str', 'Created By', 'Last Updated By', 'Created By Username', 'Created At', 'Last Updated by Username', 'Last Updated At', ];
	$x->ColFieldName = ['goal_id', 'goal_status', 'goal_description', 'goal_duration', 'goal_set_date', 'supervisor_name', 'assigned_to', 'goal_setting_str', 'created_by', 'last_updated_by', 'created_by_username', 'created_at', 'last_updated_by_username', 'last_updated_at', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/goal_setting_table_templateTV.html';
	$x->SelectedTemplate = 'templates/goal_setting_table_templateTVS.html';
	$x->TemplateDV = 'templates/goal_setting_table_templateDV.html';
	$x->TemplateDVP = 'templates/goal_setting_table_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: goal_setting_table_init
	$render = true;
	if(function_exists('goal_setting_table_init')) {
		$args = [];
		$render = goal_setting_table_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: goal_setting_table_header
	$headerCode = '';
	if(function_exists('goal_setting_table_header')) {
		$args = [];
		$headerCode = goal_setting_table_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: goal_setting_table_footer
	$footerCode = '';
	if(function_exists('goal_setting_table_footer')) {
		$args = [];
		$footerCode = goal_setting_table_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
