<?php

// Data functions (insert, update, delete, form) for table goal_setting_table

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function goal_setting_table_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('goal_setting_table');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'goal_status' => Request::val('goal_status', ''),
		'goal_description' => br2nl(Request::val('goal_description', '')),
		'goal_duration' => Request::val('goal_duration', ''),
		'goal_set_date' => Request::dateComponents('goal_set_date', '1'),
		'supervisor_name' => Request::lookup('supervisor_name', ''),
		'assigned_to' => Request::lookup('assigned_to', ''),
		'created_by' => parseCode('<%%creatorUsername%%>', true),
		'created_at' => parseCode('<%%creationDateTime%%>', true),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('goal_setting_table', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		goal_setting_table_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function goal_setting_table_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function goal_setting_table_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('goal_setting_table', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: goal_setting_table_before_delete
	if(function_exists('goal_setting_table_before_delete')) {
		$args = [];
		if(!goal_setting_table_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: ''
			);
	}

	// child table: goal_progress_table
	$res = sql("SELECT `goal_id` FROM `goal_setting_table` WHERE `goal_id`='{$selected_id}'", $eo);
	$goal_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `goal_progress_table` WHERE `goal_lookup`='" . makeSafe($goal_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	$childrenATag = '<a class="alert-link" href="goal_progress_table_view.php?filterer_goal_lookup=' . urlencode($goal_id[0]) . '">%s</a>';
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'goal_progress_table'), $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'goal_progress_table'), $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = `goal_setting_table_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = `goal_setting_table_view.php?SelectedID=' . urlencode($selected_id) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `goal_setting_table` WHERE `goal_id`='{$selected_id}'", $eo);

	// hook: goal_setting_table_after_delete
	if(function_exists('goal_setting_table_after_delete')) {
		$args = [];
		goal_setting_table_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='goal_setting_table' AND `pkValue`='{$selected_id}'", $eo);
}

function goal_setting_table_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('goal_setting_table', $selected_id, 'edit')) return false;

	$data = [
		'goal_status' => Request::val('goal_status', ''),
		'goal_description' => br2nl(Request::val('goal_description', '')),
		'goal_duration' => Request::val('goal_duration', ''),
		'goal_set_date' => Request::dateComponents('goal_set_date', ''),
		'supervisor_name' => Request::lookup('supervisor_name', ''),
		'assigned_to' => Request::lookup('assigned_to', ''),
		'last_updated_by' => parseCode('<%%editorUsername%%>', false),
		'last_updated_at' => parseCode('<%%editingDateTime%%>', false),
	];

	// get existing values
	$old_data = getRecord('goal_setting_table', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: goal_setting_table_before_update
	if(function_exists('goal_setting_table_before_update')) {
		$args = ['old_data' => $old_data];
		if(!goal_setting_table_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'goal_setting_table',
		backtick_keys_once($set),
		['`goal_id`' => $selected_id],
		$error_message
	)) {
		echo $error_message;
		echo '<a href="goal_setting_table_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	update_calc_fields('goal_setting_table', $data['selectedID'], calculated_fields()['goal_setting_table']);

	// hook: goal_setting_table_after_update
	if(function_exists('goal_setting_table_after_update')) {
		if($row = getRecord('goal_setting_table', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['goal_id'];
		$args = ['old_data' => $old_data];
		if(!goal_setting_table_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('goal_setting_table', $selected_id);
}

function goal_setting_table_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = true;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('goal_setting_table');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('goal_setting_table', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('goal_setting_table', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('goal_setting_table', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);

	$filterer_supervisor_name = Request::val('filterer_supervisor_name');
	$filterer_assigned_to = Request::val('filterer_assigned_to');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: goal_status
	$combo_goal_status = new Combo;
	$combo_goal_status->ListType = 0;
	$combo_goal_status->MultipleSeparator = ', ';
	$combo_goal_status->ListBoxHeight = 10;
	$combo_goal_status->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/goal_setting_table.goal_status.csv')) {
		$goal_status_data = addslashes(implode('', @file(__DIR__ . '/hooks/goal_setting_table.goal_status.csv')));
		$combo_goal_status->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($goal_status_data))));
		$combo_goal_status->ListData = $combo_goal_status->ListItem;
	} else {
		$combo_goal_status->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("On going;;Yet to Start;;Partially Completed;;Completed"))));
		$combo_goal_status->ListData = $combo_goal_status->ListItem;
	}
	$combo_goal_status->SelectName = 'goal_status';
	// combobox: goal_duration
	$combo_goal_duration = new Combo;
	$combo_goal_duration->ListType = 0;
	$combo_goal_duration->MultipleSeparator = ', ';
	$combo_goal_duration->ListBoxHeight = 10;
	$combo_goal_duration->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/goal_setting_table.goal_duration.csv')) {
		$goal_duration_data = addslashes(implode('', @file(__DIR__ . '/hooks/goal_setting_table.goal_duration.csv')));
		$combo_goal_duration->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($goal_duration_data))));
		$combo_goal_duration->ListData = $combo_goal_duration->ListItem;
	} else {
		$combo_goal_duration->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Day;;Week;;Fortnight;;Month;;Quarter;;Six Months;;One Year"))));
		$combo_goal_duration->ListData = $combo_goal_duration->ListItem;
	}
	$combo_goal_duration->SelectName = 'goal_duration';
	// combobox: goal_set_date
	$combo_goal_set_date = new DateCombo;
	$combo_goal_set_date->DateFormat = "dmy";
	$combo_goal_set_date->MinYear = defined('goal_setting_table.goal_set_date.MinYear') ? constant('goal_setting_table.goal_set_date.MinYear') : 1900;
	$combo_goal_set_date->MaxYear = defined('goal_setting_table.goal_set_date.MaxYear') ? constant('goal_setting_table.goal_set_date.MaxYear') : 2100;
	$combo_goal_set_date->DefaultDate = parseMySQLDate('1', '1');
	$combo_goal_set_date->MonthNames = $Translation['month names'];
	$combo_goal_set_date->NamePrefix = 'goal_set_date';
	// combobox: supervisor_name
	$combo_supervisor_name = new DataCombo;
	// combobox: assigned_to
	$combo_assigned_to = new DataCombo;

	if($hasSelectedId) {
		if(!($row = getRecord('goal_setting_table', $selectedId))) {
			return error_message($Translation['No records found'], 'goal_setting_table_view.php', false);
		}
		$combo_goal_status->SelectedData = $row['goal_status'];
		$combo_goal_duration->SelectedData = $row['goal_duration'];
		$combo_goal_set_date->DefaultDate = $row['goal_set_date'];
		$combo_supervisor_name->SelectedData = $row['supervisor_name'];
		$combo_assigned_to->SelectedData = $row['assigned_to'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_goal_status->SelectedText = (isset($filterField[1]) && $filterField[1] == '2' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
		$combo_goal_duration->SelectedText = (isset($filterField[1]) && $filterField[1] == '4' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
		$combo_supervisor_name->SelectedData = $filterer_supervisor_name;
		$combo_assigned_to->SelectedData = $filterer_assigned_to;
	}
	$combo_goal_status->Render();
	$combo_goal_duration->Render();
	$combo_supervisor_name->HTML = '<span id="supervisor_name-container' . $rnd1 . '"></span><input type="hidden" name="supervisor_name" id="supervisor_name' . $rnd1 . '" value="' . html_attr($combo_supervisor_name->SelectedData) . '">';
	$combo_supervisor_name->MatchText = '<span id="supervisor_name-container-readonly' . $rnd1 . '"></span><input type="hidden" name="supervisor_name" id="supervisor_name' . $rnd1 . '" value="' . html_attr($combo_supervisor_name->SelectedData) . '">';
	$combo_assigned_to->HTML = '<span id="assigned_to-container' . $rnd1 . '"></span><input type="hidden" name="assigned_to" id="assigned_to' . $rnd1 . '" value="' . html_attr($combo_assigned_to->SelectedData) . '">';
	$combo_assigned_to->MatchText = '<span id="assigned_to-container-readonly' . $rnd1 . '"></span><input type="hidden" name="assigned_to" id="assigned_to' . $rnd1 . '" value="' . html_attr($combo_assigned_to->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_supervisor_name__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['supervisor_name'] : htmlspecialchars($filterer_supervisor_name, ENT_QUOTES)); ?>"};
		AppGini.current_assigned_to__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['assigned_to'] : htmlspecialchars($filterer_assigned_to, ENT_QUOTES)); ?>"};

		$j(function() {
			setTimeout(function() {
				if(typeof(supervisor_name_reload__RAND__) == 'function') supervisor_name_reload__RAND__();
				if(typeof(assigned_to_reload__RAND__) == 'function') assigned_to_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function supervisor_name_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#supervisor_name-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_supervisor_name__RAND__.value, t: 'goal_setting_table', f: 'supervisor_name' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="supervisor_name"]').val(resp.results[0].id);
							$j('[id=supervisor_name-container-readonly__RAND__]').html('<span class="match-text" id="supervisor_name-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=user_table_view_parent]').hide(); } else { $j('.btn[id=user_table_view_parent]').show(); }


							if(typeof(supervisor_name_update_autofills__RAND__) == 'function') supervisor_name_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'goal_setting_table', f: 'supervisor_name' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_supervisor_name__RAND__.value = e.added.id;
				AppGini.current_supervisor_name__RAND__.text = e.added.text;
				$j('[name="supervisor_name"]').val(e.added.id);
				$j(this).parents('.form-group')
					.find('.btn[id=user_table_view_parent]')
					.toggleClass('hidden', e.added.id == '<?php echo empty_lookup_value; ?>');


				if(typeof(supervisor_name_update_autofills__RAND__) == 'function') supervisor_name_update_autofills__RAND__();
			});

			if(!$j("#supervisor_name-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_supervisor_name__RAND__.value, t: 'goal_setting_table', f: 'supervisor_name' },
					success: function(resp) {
						$j('[name="supervisor_name"]').val(resp.results[0].id);
						$j('[id=supervisor_name-container-readonly__RAND__]').html('<span class="match-text" id="supervisor_name-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=user_table_view_parent]').hide(); } else { $j('.btn[id=user_table_view_parent]').show(); }

						if(typeof(supervisor_name_update_autofills__RAND__) == 'function') supervisor_name_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_supervisor_name__RAND__.value, t: 'goal_setting_table', f: 'supervisor_name' },
				success: function(resp) {
					$j('[id=supervisor_name-container__RAND__], [id=supervisor_name-container-readonly__RAND__]').html('<span class="match-text" id="supervisor_name-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=user_table_view_parent]').hide(); } else { $j('.btn[id=user_table_view_parent]').show(); }

					if(typeof(supervisor_name_update_autofills__RAND__) == 'function') supervisor_name_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function assigned_to_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#assigned_to-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_assigned_to__RAND__.value, t: 'goal_setting_table', f: 'assigned_to' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="assigned_to"]').val(resp.results[0].id);
							$j('[id=assigned_to-container-readonly__RAND__]').html('<span class="match-text" id="assigned_to-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=user_table_view_parent]').hide(); } else { $j('.btn[id=user_table_view_parent]').show(); }


							if(typeof(assigned_to_update_autofills__RAND__) == 'function') assigned_to_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'goal_setting_table', f: 'assigned_to' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_assigned_to__RAND__.value = e.added.id;
				AppGini.current_assigned_to__RAND__.text = e.added.text;
				$j('[name="assigned_to"]').val(e.added.id);
				$j(this).parents('.form-group')
					.find('.btn[id=user_table_view_parent]')
					.toggleClass('hidden', e.added.id == '<?php echo empty_lookup_value; ?>');


				if(typeof(assigned_to_update_autofills__RAND__) == 'function') assigned_to_update_autofills__RAND__();
			});

			if(!$j("#assigned_to-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_assigned_to__RAND__.value, t: 'goal_setting_table', f: 'assigned_to' },
					success: function(resp) {
						$j('[name="assigned_to"]').val(resp.results[0].id);
						$j('[id=assigned_to-container-readonly__RAND__]').html('<span class="match-text" id="assigned_to-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=user_table_view_parent]').hide(); } else { $j('.btn[id=user_table_view_parent]').show(); }

						if(typeof(assigned_to_update_autofills__RAND__) == 'function') assigned_to_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_assigned_to__RAND__.value, t: 'goal_setting_table', f: 'assigned_to' },
				success: function(resp) {
					$j('[id=assigned_to-container__RAND__], [id=assigned_to-container-readonly__RAND__]').html('<span class="match-text" id="assigned_to-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=user_table_view_parent]').hide(); } else { $j('.btn[id=user_table_view_parent]').show(); }

					if(typeof(assigned_to_update_autofills__RAND__) == 'function') assigned_to_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/goal_setting_table_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/goal_setting_table_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Goal setting table details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default ltr" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>',
				'<button
					type="submit"
					class="btn btn-default ltr"
					id="deselect"
					name="deselect_x"
					value="1"
					onclick="' . $backAction . '"
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#goal_status').replaceWith('<div class=\"form-control-static\" id=\"goal_status\">' + (\$j('#goal_status').val() || '') + '</div>'); \$j('#goal_status-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#goal_description').replaceWith('<div class=\"form-control-static\" id=\"goal_description\">' + (\$j('#goal_description').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#goal_duration').replaceWith('<div class=\"form-control-static\" id=\"goal_duration\">' + (\$j('#goal_duration').val() || '') + '</div>'); \$j('#goal_duration-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#goal_set_date').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#goal_set_dateDay, #goal_set_dateMonth, #goal_set_dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#supervisor_name').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#supervisor_name_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\t\$j('#assigned_to').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#assigned_to_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(goal_status)%%>', $combo_goal_status->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(goal_status)%%>', $combo_goal_status->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(goal_duration)%%>', $combo_goal_duration->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(goal_duration)%%>', $combo_goal_duration->SelectedData, $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(goal_set_date)%%>',
		(!$fieldsAreEditable ?
			'<div class="form-control-static">' . $combo_goal_set_date->GetHTML(true) . '</div>' :
			$combo_goal_set_date->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(goal_set_date)%%>', $combo_goal_set_date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(supervisor_name)%%>', $combo_supervisor_name->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(supervisor_name)%%>', $combo_supervisor_name->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(supervisor_name)%%>', urlencode($combo_supervisor_name->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(assigned_to)%%>', $combo_assigned_to->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(assigned_to)%%>', $combo_assigned_to->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(assigned_to)%%>', urlencode($combo_assigned_to->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['supervisor_name' => ['user_table', 'Supervisor name'], 'assigned_to' => ['user_table', 'Assigned to'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(goal_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(goal_status)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(goal_description)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(goal_duration)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(goal_set_date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(supervisor_name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(assigned_to)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(goal_setting_str)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_by_username)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_at)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_by_username)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_at)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		$templateCode = str_replace('<%%VALUE(goal_id)%%>', safe_html($urow['goal_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(goal_id)%%>', urlencode($urow['goal_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(goal_status)%%>', safe_html($urow['goal_status']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(goal_status)%%>', html_attr($row['goal_status']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(goal_status)%%>', urlencode($urow['goal_status']), $templateCode);
		$templateCode = str_replace('<%%VALUE(goal_description)%%>', safe_html($urow['goal_description'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(goal_description)%%>', urlencode($urow['goal_description']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(goal_duration)%%>', safe_html($urow['goal_duration']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(goal_duration)%%>', html_attr($row['goal_duration']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(goal_duration)%%>', urlencode($urow['goal_duration']), $templateCode);
		$templateCode = str_replace('<%%VALUE(goal_set_date)%%>', app_datetime($row['goal_set_date']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(goal_set_date)%%>', urlencode(app_datetime($urow['goal_set_date'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(supervisor_name)%%>', safe_html($urow['supervisor_name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(supervisor_name)%%>', html_attr($row['supervisor_name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(supervisor_name)%%>', urlencode($urow['supervisor_name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(assigned_to)%%>', safe_html($urow['assigned_to']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(assigned_to)%%>', html_attr($row['assigned_to']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(assigned_to)%%>', urlencode($urow['assigned_to']), $templateCode);
		$templateCode = str_replace('<%%VALUE(goal_setting_str)%%>', safe_html($urow['goal_setting_str'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(goal_setting_str)%%>', urlencode($urow['goal_setting_str']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', safe_html($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by)%%>', safe_html($urow['last_updated_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by)%%>', urlencode($urow['last_updated_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by_username)%%>', safe_html($urow['created_by_username']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by_username)%%>', urlencode($urow['created_by_username']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_at)%%>', safe_html($urow['created_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode($urow['created_at']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by_username)%%>', safe_html($urow['last_updated_by_username']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by_username)%%>', urlencode($urow['last_updated_by_username']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_at)%%>', safe_html($urow['last_updated_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_at)%%>', urlencode($urow['last_updated_at']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(goal_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(goal_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(goal_status)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(goal_status)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(goal_description)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(goal_description)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(goal_duration)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(goal_duration)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(goal_set_date)%%>', '1', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(goal_set_date)%%>', urlencode('1'), $templateCode);
		$templateCode = str_replace('<%%VALUE(supervisor_name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(supervisor_name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(assigned_to)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(assigned_to)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(goal_setting_str)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(goal_setting_str)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by)%%>', '<%%editorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by)%%>', urlencode('<%%editorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by_username)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by_username)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_at)%%>', '<%%creationDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode('<%%creationDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by_username)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by_username)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_at)%%>', '<%%editingDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_at)%%>', urlencode('<%%editingDateTime%%>'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('goal_setting_table');
	if($hasSelectedId) {
		$jdata = get_joined_record('goal_setting_table', $selectedId);
		if($jdata === false) $jdata = get_defaults('goal_setting_table');
		$rdata = $row;
	}
	$templateCode .= loadView('goal_setting_table-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: goal_setting_table_dv
	if(function_exists('goal_setting_table_dv')) {
		$args = [];
		goal_setting_table_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}