<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/it_inventory_app.php');
	include_once(__DIR__ . '/it_inventory_app_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('it_inventory_app');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'it_inventory_app';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`it_inventory_app`.`it_inventory_id`" => "it_inventory_id",
		"`it_inventory_app`.`username`" => "username",
		"if(`it_inventory_app`.`date`,date_format(`it_inventory_app`.`date`,'%d/%m/%Y'),'')" => "date",
		"`it_inventory_app`.`description`" => "description",
		"`it_inventory_app`.`classification_of_asset`" => "classification_of_asset",
		"`it_inventory_app`.`sub_category`" => "sub_category",
		"`it_inventory_app`.`qty`" => "qty",
		"`it_inventory_app`.`asset_serial_number`" => "asset_serial_number",
		"`it_inventory_app`.`qr_and_bar_code`" => "qr_and_bar_code",
		"`it_inventory_app`.`custody_department`" => "custody_department",
		"`it_inventory_app`.`custodian`" => "custodian",
		"`it_inventory_app`.`custodian_signature`" => "custodian_signature",
		"`it_inventory_app`.`no_of_years_useful_life_of_assets`" => "no_of_years_useful_life_of_assets",
		"if(`it_inventory_app`.`date_of_useful_life_of_assets_ends`,date_format(`it_inventory_app`.`date_of_useful_life_of_assets_ends`,'%d/%m/%Y'),'')" => "date_of_useful_life_of_assets_ends",
		"`it_inventory_app`.`remarks`" => "remarks",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Sactioned by */" => "sactioned_by",
		"`it_inventory_app`.`it_inventory_str`" => "it_inventory_str",
		"`it_inventory_app`.`last_updated_by`" => "last_updated_by",
		"`it_inventory_app`.`last_updated_at`" => "last_updated_at",
		"`it_inventory_app`.`created_by`" => "created_by",
		"`it_inventory_app`.`created_by_username`" => "created_by_username",
		"`it_inventory_app`.`created_at`" => "created_at",
		"`it_inventory_app`.`last_updated_by_username`" => "last_updated_by_username",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`it_inventory_app`.`it_inventory_id`',
		2 => 2,
		3 => '`it_inventory_app`.`date`',
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => '`it_inventory_app`.`date_of_useful_life_of_assets_ends`',
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19,
		20 => 20,
		21 => 21,
		22 => 22,
		23 => 23,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`it_inventory_app`.`it_inventory_id`" => "it_inventory_id",
		"`it_inventory_app`.`username`" => "username",
		"if(`it_inventory_app`.`date`,date_format(`it_inventory_app`.`date`,'%d/%m/%Y'),'')" => "date",
		"`it_inventory_app`.`description`" => "description",
		"`it_inventory_app`.`classification_of_asset`" => "classification_of_asset",
		"`it_inventory_app`.`sub_category`" => "sub_category",
		"`it_inventory_app`.`qty`" => "qty",
		"`it_inventory_app`.`asset_serial_number`" => "asset_serial_number",
		"`it_inventory_app`.`qr_and_bar_code`" => "qr_and_bar_code",
		"`it_inventory_app`.`custody_department`" => "custody_department",
		"`it_inventory_app`.`custodian`" => "custodian",
		"`it_inventory_app`.`custodian_signature`" => "custodian_signature",
		"`it_inventory_app`.`no_of_years_useful_life_of_assets`" => "no_of_years_useful_life_of_assets",
		"if(`it_inventory_app`.`date_of_useful_life_of_assets_ends`,date_format(`it_inventory_app`.`date_of_useful_life_of_assets_ends`,'%d/%m/%Y'),'')" => "date_of_useful_life_of_assets_ends",
		"`it_inventory_app`.`remarks`" => "remarks",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Sactioned by */" => "sactioned_by",
		"`it_inventory_app`.`it_inventory_str`" => "it_inventory_str",
		"`it_inventory_app`.`last_updated_by`" => "last_updated_by",
		"`it_inventory_app`.`last_updated_at`" => "last_updated_at",
		"`it_inventory_app`.`created_by`" => "created_by",
		"`it_inventory_app`.`created_by_username`" => "created_by_username",
		"`it_inventory_app`.`created_at`" => "created_at",
		"`it_inventory_app`.`last_updated_by_username`" => "last_updated_by_username",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`it_inventory_app`.`it_inventory_id`" => "ID",
		"`it_inventory_app`.`username`" => "Username",
		"`it_inventory_app`.`date`" => "Date",
		"`it_inventory_app`.`description`" => "Description",
		"`it_inventory_app`.`classification_of_asset`" => "Classification of asset",
		"`it_inventory_app`.`sub_category`" => "Sub category",
		"`it_inventory_app`.`qty`" => "Qty",
		"`it_inventory_app`.`asset_serial_number`" => "Asset serial number",
		"`it_inventory_app`.`qr_and_bar_code`" => "Qr and bar code",
		"`it_inventory_app`.`custody_department`" => "Custody department",
		"`it_inventory_app`.`custodian`" => "Custodian",
		"`it_inventory_app`.`no_of_years_useful_life_of_assets`" => "Number of years useful life of assets",
		"`it_inventory_app`.`date_of_useful_life_of_assets_ends`" => "Date of useful life of assets ends",
		"`it_inventory_app`.`remarks`" => "Remarks",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Sactioned by */" => "Sactioned by",
		"`it_inventory_app`.`it_inventory_str`" => "It inventory str",
		"`it_inventory_app`.`last_updated_by`" => "Last updated by",
		"`it_inventory_app`.`last_updated_at`" => "Last updated at",
		"`it_inventory_app`.`created_by`" => "Created By",
		"`it_inventory_app`.`created_by_username`" => "Created By Username",
		"`it_inventory_app`.`created_at`" => "Created At",
		"`it_inventory_app`.`last_updated_by_username`" => "Last Updated by Username",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`it_inventory_app`.`it_inventory_id`" => "it_inventory_id",
		"`it_inventory_app`.`username`" => "username",
		"if(`it_inventory_app`.`date`,date_format(`it_inventory_app`.`date`,'%d/%m/%Y'),'')" => "date",
		"`it_inventory_app`.`description`" => "description",
		"`it_inventory_app`.`classification_of_asset`" => "classification_of_asset",
		"`it_inventory_app`.`sub_category`" => "sub_category",
		"`it_inventory_app`.`qty`" => "qty",
		"`it_inventory_app`.`asset_serial_number`" => "asset_serial_number",
		"`it_inventory_app`.`qr_and_bar_code`" => "qr_and_bar_code",
		"`it_inventory_app`.`custody_department`" => "custody_department",
		"`it_inventory_app`.`custodian`" => "custodian",
		"`it_inventory_app`.`no_of_years_useful_life_of_assets`" => "no_of_years_useful_life_of_assets",
		"if(`it_inventory_app`.`date_of_useful_life_of_assets_ends`,date_format(`it_inventory_app`.`date_of_useful_life_of_assets_ends`,'%d/%m/%Y'),'')" => "date_of_useful_life_of_assets_ends",
		"`it_inventory_app`.`remarks`" => "remarks",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Sactioned by */" => "sactioned_by",
		"`it_inventory_app`.`it_inventory_str`" => "it_inventory_str",
		"`it_inventory_app`.`last_updated_by`" => "last_updated_by",
		"`it_inventory_app`.`last_updated_at`" => "last_updated_at",
		"`it_inventory_app`.`created_by`" => "created_by",
		"`it_inventory_app`.`created_by_username`" => "created_by_username",
		"`it_inventory_app`.`created_at`" => "created_at",
		"`it_inventory_app`.`last_updated_by_username`" => "last_updated_by_username",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['sactioned_by' => 'Sactioned by', ];

	$x->QueryFrom = "`it_inventory_app` LEFT JOIN `user_table` as user_table1 ON `user_table1`.`user_id`=`it_inventory_app`.`sactioned_by` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'it_inventory_app_view.php';
	$x->TableTitle = 'IT inventory - App';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`it_inventory_app`.`it_inventory_id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Date', 'Description', 'Classification of asset', 'Sub category', 'Qty', 'Asset serial number', 'Qr and bar code', 'Custody department', 'Custodian', 'Custodian signature', 'Number of years useful life of assets', 'Date of useful life of assets ends', 'Remarks', 'Sactioned by', 'It inventory str', 'Last updated by', 'Last updated at', 'Created By', 'Created By Username', 'Created At', 'Last Updated by Username', ];
	$x->ColFieldName = ['it_inventory_id', 'date', 'description', 'classification_of_asset', 'sub_category', 'qty', 'asset_serial_number', 'qr_and_bar_code', 'custody_department', 'custodian', 'custodian_signature', 'no_of_years_useful_life_of_assets', 'date_of_useful_life_of_assets_ends', 'remarks', 'sactioned_by', 'it_inventory_str', 'last_updated_by', 'last_updated_at', 'created_by', 'created_by_username', 'created_at', 'last_updated_by_username', ];
	$x->ColNumber  = [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/it_inventory_app_templateTV.html';
	$x->SelectedTemplate = 'templates/it_inventory_app_templateTVS.html';
	$x->TemplateDV = 'templates/it_inventory_app_templateDV.html';
	$x->TemplateDVP = 'templates/it_inventory_app_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: it_inventory_app_init
	$render = true;
	if(function_exists('it_inventory_app_init')) {
		$args = [];
		$render = it_inventory_app_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: it_inventory_app_header
	$headerCode = '';
	if(function_exists('it_inventory_app_header')) {
		$args = [];
		$headerCode = it_inventory_app_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: it_inventory_app_footer
	$footerCode = '';
	if(function_exists('it_inventory_app_footer')) {
		$args = [];
		$footerCode = it_inventory_app_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
