<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/navavishkar_stay_facilities_allotment_table.php');
	include_once(__DIR__ . '/navavishkar_stay_facilities_allotment_table_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('navavishkar_stay_facilities_allotment_table');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'navavishkar_stay_facilities_allotment_table';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`navavishkar_stay_facilities_allotment_table`.`id`" => "id",
		"IF(    CHAR_LENGTH(`navavishkar_stay_facilities_table1`.`type_of_item`) || CHAR_LENGTH(`navavishkar_stay_facilities_table1`.`ItemDescription`), CONCAT_WS('',   `navavishkar_stay_facilities_table1`.`type_of_item`, ' ~ ', `navavishkar_stay_facilities_table1`.`ItemDescription`), '') /* Asset Details */" => "item_lookup",
		"IF(    CHAR_LENGTH(`user_table1`.`name`) || CHAR_LENGTH(`user_table1`.`memberID`), CONCAT_WS('',   `user_table1`.`name`, ' ~ ', `user_table1`.`memberID`), '') /* Select employee */" => "select_employee",
		"`navavishkar_stay_facilities_allotment_table`.`department`" => "department",
		"if(`navavishkar_stay_facilities_allotment_table`.`date`,date_format(`navavishkar_stay_facilities_allotment_table`.`date`,'%d/%m/%Y'),'')" => "date",
		"`navavishkar_stay_facilities_allotment_table`.`purpose`" => "purpose",
		"IF(    CHAR_LENGTH(`user_table2`.`name`) || CHAR_LENGTH(`user_table2`.`memberID`), CONCAT_WS('',   `user_table2`.`name`, ' ~ ', `user_table2`.`memberID`), '') /* Alloted by */" => "alloted_by",
		"`navavishkar_stay_facilities_allotment_table`.`status`" => "status",
		"if(`navavishkar_stay_facilities_allotment_table`.`returned_date`,date_format(`navavishkar_stay_facilities_allotment_table`.`returned_date`,'%d/%m/%Y'),'')" => "returned_date",
		"`navavishkar_stay_facilities_allotment_table`.`created_by_username`" => "created_by_username",
		"`navavishkar_stay_facilities_allotment_table`.`created_at`" => "created_at",
		"`navavishkar_stay_facilities_allotment_table`.`last_updated_by_username`" => "last_updated_by_username",
		"`navavishkar_stay_facilities_allotment_table`.`last_updated_at`" => "last_updated_at",
		"`navavishkar_stay_facilities_allotment_table`.`created_by`" => "created_by",
		"`navavishkar_stay_facilities_allotment_table`.`last_updated_by`" => "last_updated_by",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`navavishkar_stay_facilities_allotment_table`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`navavishkar_stay_facilities_allotment_table`.`date`',
		6 => 6,
		7 => 7,
		8 => 8,
		9 => '`navavishkar_stay_facilities_allotment_table`.`returned_date`',
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`navavishkar_stay_facilities_allotment_table`.`id`" => "id",
		"IF(    CHAR_LENGTH(`navavishkar_stay_facilities_table1`.`type_of_item`) || CHAR_LENGTH(`navavishkar_stay_facilities_table1`.`ItemDescription`), CONCAT_WS('',   `navavishkar_stay_facilities_table1`.`type_of_item`, ' ~ ', `navavishkar_stay_facilities_table1`.`ItemDescription`), '') /* Asset Details */" => "item_lookup",
		"IF(    CHAR_LENGTH(`user_table1`.`name`) || CHAR_LENGTH(`user_table1`.`memberID`), CONCAT_WS('',   `user_table1`.`name`, ' ~ ', `user_table1`.`memberID`), '') /* Select employee */" => "select_employee",
		"`navavishkar_stay_facilities_allotment_table`.`department`" => "department",
		"if(`navavishkar_stay_facilities_allotment_table`.`date`,date_format(`navavishkar_stay_facilities_allotment_table`.`date`,'%d/%m/%Y'),'')" => "date",
		"`navavishkar_stay_facilities_allotment_table`.`purpose`" => "purpose",
		"IF(    CHAR_LENGTH(`user_table2`.`name`) || CHAR_LENGTH(`user_table2`.`memberID`), CONCAT_WS('',   `user_table2`.`name`, ' ~ ', `user_table2`.`memberID`), '') /* Alloted by */" => "alloted_by",
		"`navavishkar_stay_facilities_allotment_table`.`status`" => "status",
		"if(`navavishkar_stay_facilities_allotment_table`.`returned_date`,date_format(`navavishkar_stay_facilities_allotment_table`.`returned_date`,'%d/%m/%Y'),'')" => "returned_date",
		"`navavishkar_stay_facilities_allotment_table`.`created_by_username`" => "created_by_username",
		"`navavishkar_stay_facilities_allotment_table`.`created_at`" => "created_at",
		"`navavishkar_stay_facilities_allotment_table`.`last_updated_by_username`" => "last_updated_by_username",
		"`navavishkar_stay_facilities_allotment_table`.`last_updated_at`" => "last_updated_at",
		"`navavishkar_stay_facilities_allotment_table`.`created_by`" => "created_by",
		"`navavishkar_stay_facilities_allotment_table`.`last_updated_by`" => "last_updated_by",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`navavishkar_stay_facilities_allotment_table`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`navavishkar_stay_facilities_table1`.`type_of_item`) || CHAR_LENGTH(`navavishkar_stay_facilities_table1`.`ItemDescription`), CONCAT_WS('',   `navavishkar_stay_facilities_table1`.`type_of_item`, ' ~ ', `navavishkar_stay_facilities_table1`.`ItemDescription`), '') /* Asset Details */" => "Asset Details",
		"IF(    CHAR_LENGTH(`user_table1`.`name`) || CHAR_LENGTH(`user_table1`.`memberID`), CONCAT_WS('',   `user_table1`.`name`, ' ~ ', `user_table1`.`memberID`), '') /* Select employee */" => "Select employee",
		"`navavishkar_stay_facilities_allotment_table`.`department`" => "Department",
		"`navavishkar_stay_facilities_allotment_table`.`date`" => "Date",
		"`navavishkar_stay_facilities_allotment_table`.`purpose`" => "Purpose",
		"IF(    CHAR_LENGTH(`user_table2`.`name`) || CHAR_LENGTH(`user_table2`.`memberID`), CONCAT_WS('',   `user_table2`.`name`, ' ~ ', `user_table2`.`memberID`), '') /* Alloted by */" => "Alloted by",
		"`navavishkar_stay_facilities_allotment_table`.`status`" => "Status",
		"`navavishkar_stay_facilities_allotment_table`.`returned_date`" => "Returned Date",
		"`navavishkar_stay_facilities_allotment_table`.`created_by_username`" => "Created by Username",
		"`navavishkar_stay_facilities_allotment_table`.`created_at`" => "Created At",
		"`navavishkar_stay_facilities_allotment_table`.`last_updated_by_username`" => "Last Updated By Username",
		"`navavishkar_stay_facilities_allotment_table`.`last_updated_at`" => "Last updated at",
		"`navavishkar_stay_facilities_allotment_table`.`created_by`" => "Created By",
		"`navavishkar_stay_facilities_allotment_table`.`last_updated_by`" => "Last updated by",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`navavishkar_stay_facilities_allotment_table`.`id`" => "id",
		"IF(    CHAR_LENGTH(`navavishkar_stay_facilities_table1`.`type_of_item`) || CHAR_LENGTH(`navavishkar_stay_facilities_table1`.`ItemDescription`), CONCAT_WS('',   `navavishkar_stay_facilities_table1`.`type_of_item`, ' ~ ', `navavishkar_stay_facilities_table1`.`ItemDescription`), '') /* Asset Details */" => "item_lookup",
		"IF(    CHAR_LENGTH(`user_table1`.`name`) || CHAR_LENGTH(`user_table1`.`memberID`), CONCAT_WS('',   `user_table1`.`name`, ' ~ ', `user_table1`.`memberID`), '') /* Select employee */" => "select_employee",
		"`navavishkar_stay_facilities_allotment_table`.`department`" => "department",
		"if(`navavishkar_stay_facilities_allotment_table`.`date`,date_format(`navavishkar_stay_facilities_allotment_table`.`date`,'%d/%m/%Y'),'')" => "date",
		"`navavishkar_stay_facilities_allotment_table`.`purpose`" => "purpose",
		"IF(    CHAR_LENGTH(`user_table2`.`name`) || CHAR_LENGTH(`user_table2`.`memberID`), CONCAT_WS('',   `user_table2`.`name`, ' ~ ', `user_table2`.`memberID`), '') /* Alloted by */" => "alloted_by",
		"`navavishkar_stay_facilities_allotment_table`.`status`" => "status",
		"if(`navavishkar_stay_facilities_allotment_table`.`returned_date`,date_format(`navavishkar_stay_facilities_allotment_table`.`returned_date`,'%d/%m/%Y'),'')" => "returned_date",
		"`navavishkar_stay_facilities_allotment_table`.`created_by_username`" => "created_by_username",
		"`navavishkar_stay_facilities_allotment_table`.`created_at`" => "created_at",
		"`navavishkar_stay_facilities_allotment_table`.`last_updated_by_username`" => "last_updated_by_username",
		"`navavishkar_stay_facilities_allotment_table`.`last_updated_at`" => "last_updated_at",
		"`navavishkar_stay_facilities_allotment_table`.`created_by`" => "created_by",
		"`navavishkar_stay_facilities_allotment_table`.`last_updated_by`" => "last_updated_by",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['item_lookup' => 'Asset Details', 'select_employee' => 'Select employee', 'alloted_by' => 'Alloted by', ];

	$x->QueryFrom = "`navavishkar_stay_facilities_allotment_table` LEFT JOIN `navavishkar_stay_facilities_table` as navavishkar_stay_facilities_table1 ON `navavishkar_stay_facilities_table1`.`id`=`navavishkar_stay_facilities_allotment_table`.`item_lookup` LEFT JOIN `user_table` as user_table1 ON `user_table1`.`user_id`=`navavishkar_stay_facilities_allotment_table`.`select_employee` LEFT JOIN `user_table` as user_table2 ON `user_table2`.`user_id`=`navavishkar_stay_facilities_allotment_table`.`alloted_by` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'navavishkar_stay_facilities_allotment_table_view.php';
	$x->TableTitle = 'Navavishkar Stay Facilities - App';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`navavishkar_stay_facilities_allotment_table`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Asset Details', 'Select employee', 'Department', 'Date', 'Purpose', 'Alloted by', 'Status', 'Returned Date', 'Created by Username', 'Created At', 'Last Updated By Username', 'Last updated at', ];
	$x->ColFieldName = ['id', 'item_lookup', 'select_employee', 'department', 'date', 'purpose', 'alloted_by', 'status', 'returned_date', 'created_by_username', 'created_at', 'last_updated_by_username', 'last_updated_at', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/navavishkar_stay_facilities_allotment_table_templateTV.html';
	$x->SelectedTemplate = 'templates/navavishkar_stay_facilities_allotment_table_templateTVS.html';
	$x->TemplateDV = 'templates/navavishkar_stay_facilities_allotment_table_templateDV.html';
	$x->TemplateDVP = 'templates/navavishkar_stay_facilities_allotment_table_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: navavishkar_stay_facilities_allotment_table_init
	$render = true;
	if(function_exists('navavishkar_stay_facilities_allotment_table_init')) {
		$args = [];
		$render = navavishkar_stay_facilities_allotment_table_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: navavishkar_stay_facilities_allotment_table_header
	$headerCode = '';
	if(function_exists('navavishkar_stay_facilities_allotment_table_header')) {
		$args = [];
		$headerCode = navavishkar_stay_facilities_allotment_table_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: navavishkar_stay_facilities_allotment_table_footer
	$footerCode = '';
	if(function_exists('navavishkar_stay_facilities_allotment_table_footer')) {
		$args = [];
		$footerCode = navavishkar_stay_facilities_allotment_table_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
