<?php

// Data functions (insert, update, delete, form) for table panel_decision_table_tdp

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function panel_decision_table_tdp_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('panel_decision_table_tdp');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'edition' => Request::val('edition', ''),
		'project_id' => Request::val('project_id', ''),
		'date_of_presentation' => Request::dateComponents('date_of_presentation', ''),
		'project_title' => Request::val('project_title', ''),
		'name_of_pi' => Request::val('name_of_pi', ''),
		'mobile_number' => Request::val('mobile_number', ''),
		'institute' => Request::val('institute', ''),
		'budget_specified' => Request::val('budget_specified', ''),
		'final_budget_to_be_allocated' => Request::val('final_budget_to_be_allocated', ''),
		'experts_comments' => br2nl(Request::val('experts_comments', '')),
		'trl' => Request::val('trl', ''),
		'proposal_link' => Request::val('proposal_link', ''),
		'updated_proposal_link' => Request::val('updated_proposal_link', ''),
		'where_budget_need' => br2nl(Request::val('where_budget_need', '')),
		'final_decision' => Request::val('final_decision', ''),
		'notification_mail' => Request::val('notification_mail', ''),
		'call_done' => br2nl(Request::val('call_done', '')),
		'created_by' => parseCode('<%%creatorUsername%%>', true),
		'created_at' => parseCode('<%%creationDateTime%%>', true),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('panel_decision_table_tdp', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		panel_decision_table_tdp_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function panel_decision_table_tdp_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function panel_decision_table_tdp_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('panel_decision_table_tdp', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: panel_decision_table_tdp_before_delete
	if(function_exists('panel_decision_table_tdp_before_delete')) {
		$args = [];
		if(!panel_decision_table_tdp_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: ''
			);
	}

	// child table: selected_proposals_final_tdp
	$res = sql("SELECT `panel_decision_id` FROM `panel_decision_table_tdp` WHERE `panel_decision_id`='{$selected_id}'", $eo);
	$panel_decision_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `selected_proposals_final_tdp` WHERE `project_id`='" . makeSafe($panel_decision_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	$childrenATag = '<a class="alert-link" href="selected_proposals_final_tdp_view.php?filterer_project_id=' . urlencode($panel_decision_id[0]) . '">%s</a>';
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'selected_proposals_final_tdp'), $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'selected_proposals_final_tdp'), $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = `panel_decision_table_tdp_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = `panel_decision_table_tdp_view.php?SelectedID=' . urlencode($selected_id) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		return $RetMsg;
	}

	// child table: stage_wise_budget_table_tdp
	$res = sql("SELECT `panel_decision_id` FROM `panel_decision_table_tdp` WHERE `panel_decision_id`='{$selected_id}'", $eo);
	$panel_decision_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `stage_wise_budget_table_tdp` WHERE `project_id`='" . makeSafe($panel_decision_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	$childrenATag = '<a class="alert-link" href="stage_wise_budget_table_tdp_view.php?filterer_project_id=' . urlencode($panel_decision_id[0]) . '">%s</a>';
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'stage_wise_budget_table_tdp'), $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'stage_wise_budget_table_tdp'), $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = `panel_decision_table_tdp_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = `panel_decision_table_tdp_view.php?SelectedID=' . urlencode($selected_id) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		return $RetMsg;
	}

	// child table: first_level_shortlisted_proposals_tdp
	$res = sql("SELECT `panel_decision_id` FROM `panel_decision_table_tdp` WHERE `panel_decision_id`='{$selected_id}'", $eo);
	$panel_decision_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `first_level_shortlisted_proposals_tdp` WHERE `project_id`='" . makeSafe($panel_decision_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	$childrenATag = '<a class="alert-link" href="first_level_shortlisted_proposals_tdp_view.php?filterer_project_id=' . urlencode($panel_decision_id[0]) . '">%s</a>';
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'first_level_shortlisted_proposals_tdp'), $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'first_level_shortlisted_proposals_tdp'), $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = `panel_decision_table_tdp_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = `panel_decision_table_tdp_view.php?SelectedID=' . urlencode($selected_id) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		return $RetMsg;
	}

	// child table: budget_table_tdp
	$res = sql("SELECT `panel_decision_id` FROM `panel_decision_table_tdp` WHERE `panel_decision_id`='{$selected_id}'", $eo);
	$panel_decision_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `budget_table_tdp` WHERE `project_id`='" . makeSafe($panel_decision_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	$childrenATag = '<a class="alert-link" href="budget_table_tdp_view.php?filterer_project_id=' . urlencode($panel_decision_id[0]) . '">%s</a>';
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'budget_table_tdp'), $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'budget_table_tdp'), $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = `panel_decision_table_tdp_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = `panel_decision_table_tdp_view.php?SelectedID=' . urlencode($selected_id) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		return $RetMsg;
	}

	// child table: panel_comments_tdp
	$res = sql("SELECT `panel_decision_id` FROM `panel_decision_table_tdp` WHERE `panel_decision_id`='{$selected_id}'", $eo);
	$panel_decision_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `panel_comments_tdp` WHERE `project_id`='" . makeSafe($panel_decision_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	$childrenATag = '<a class="alert-link" href="panel_comments_tdp_view.php?filterer_project_id=' . urlencode($panel_decision_id[0]) . '">%s</a>';
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'panel_comments_tdp'), $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'panel_comments_tdp'), $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = `panel_decision_table_tdp_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = `panel_decision_table_tdp_view.php?SelectedID=' . urlencode($selected_id) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		return $RetMsg;
	}

	// child table: selected_tdp
	$res = sql("SELECT `panel_decision_id` FROM `panel_decision_table_tdp` WHERE `panel_decision_id`='{$selected_id}'", $eo);
	$panel_decision_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `selected_tdp` WHERE `project_id`='" . makeSafe($panel_decision_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	$childrenATag = '<a class="alert-link" href="selected_tdp_view.php?filterer_project_id=' . urlencode($panel_decision_id[0]) . '">%s</a>';
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'selected_tdp'), $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'selected_tdp'), $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = `panel_decision_table_tdp_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = `panel_decision_table_tdp_view.php?SelectedID=' . urlencode($selected_id) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		return $RetMsg;
	}

	// child table: address_tdp
	$res = sql("SELECT `panel_decision_id` FROM `panel_decision_table_tdp` WHERE `panel_decision_id`='{$selected_id}'", $eo);
	$panel_decision_id = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `address_tdp` WHERE `project_id`='" . makeSafe($panel_decision_id[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	$childrenATag = '<a class="alert-link" href="address_tdp_view.php?filterer_project_id=' . urlencode($panel_decision_id[0]) . '">%s</a>';
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'address_tdp'), $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', sprintf($childrenATag, $rirow[0]), $RetMsg);
		$RetMsg = str_replace(['[<TableName>]', '<TableName>'], sprintf($childrenATag, 'address_tdp'), $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = `panel_decision_table_tdp_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = `panel_decision_table_tdp_view.php?SelectedID=' . urlencode($selected_id) . (Request::val('Embedded') ? '&Embedded=1' : '') . '`;">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `panel_decision_table_tdp` WHERE `panel_decision_id`='{$selected_id}'", $eo);

	// hook: panel_decision_table_tdp_after_delete
	if(function_exists('panel_decision_table_tdp_after_delete')) {
		$args = [];
		panel_decision_table_tdp_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='panel_decision_table_tdp' AND `pkValue`='{$selected_id}'", $eo);
}

function panel_decision_table_tdp_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('panel_decision_table_tdp', $selected_id, 'edit')) return false;

	$data = [
		'edition' => Request::val('edition', ''),
		'project_id' => Request::val('project_id', ''),
		'date_of_presentation' => Request::dateComponents('date_of_presentation', ''),
		'project_title' => Request::val('project_title', ''),
		'name_of_pi' => Request::val('name_of_pi', ''),
		'mobile_number' => Request::val('mobile_number', ''),
		'institute' => Request::val('institute', ''),
		'budget_specified' => Request::val('budget_specified', ''),
		'final_budget_to_be_allocated' => Request::val('final_budget_to_be_allocated', ''),
		'experts_comments' => br2nl(Request::val('experts_comments', '')),
		'trl' => Request::val('trl', ''),
		'proposal_link' => Request::val('proposal_link', ''),
		'updated_proposal_link' => Request::val('updated_proposal_link', ''),
		'where_budget_need' => br2nl(Request::val('where_budget_need', '')),
		'final_decision' => Request::val('final_decision', ''),
		'notification_mail' => Request::val('notification_mail', ''),
		'call_done' => br2nl(Request::val('call_done', '')),
		'last_updated_by' => parseCode('<%%editorUsername%%>', false),
		'last_updated_at' => parseCode('<%%editingDateTime%%>', false),
	];

	// get existing values
	$old_data = getRecord('panel_decision_table_tdp', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: panel_decision_table_tdp_before_update
	if(function_exists('panel_decision_table_tdp_before_update')) {
		$args = ['old_data' => $old_data];
		if(!panel_decision_table_tdp_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'panel_decision_table_tdp',
		backtick_keys_once($set),
		['`panel_decision_id`' => $selected_id],
		$error_message
	)) {
		echo $error_message;
		echo '<a href="panel_decision_table_tdp_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	update_calc_fields('panel_decision_table_tdp', $data['selectedID'], calculated_fields()['panel_decision_table_tdp']);

	// hook: panel_decision_table_tdp_after_update
	if(function_exists('panel_decision_table_tdp_after_update')) {
		if($row = getRecord('panel_decision_table_tdp', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['panel_decision_id'];
		$args = ['old_data' => $old_data];
		if(!panel_decision_table_tdp_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('panel_decision_table_tdp', $selected_id);
}

function panel_decision_table_tdp_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = true;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('panel_decision_table_tdp');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('panel_decision_table_tdp', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('panel_decision_table_tdp', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('panel_decision_table_tdp', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: date_of_presentation
	$combo_date_of_presentation = new DateCombo;
	$combo_date_of_presentation->DateFormat = "dmy";
	$combo_date_of_presentation->MinYear = defined('panel_decision_table_tdp.date_of_presentation.MinYear') ? constant('panel_decision_table_tdp.date_of_presentation.MinYear') : 1900;
	$combo_date_of_presentation->MaxYear = defined('panel_decision_table_tdp.date_of_presentation.MaxYear') ? constant('panel_decision_table_tdp.date_of_presentation.MaxYear') : 2100;
	$combo_date_of_presentation->DefaultDate = parseMySQLDate('', '');
	$combo_date_of_presentation->MonthNames = $Translation['month names'];
	$combo_date_of_presentation->NamePrefix = 'date_of_presentation';
	// combobox: notification_mail
	$combo_notification_mail = new Combo;
	$combo_notification_mail->ListType = 0;
	$combo_notification_mail->MultipleSeparator = ', ';
	$combo_notification_mail->ListBoxHeight = 10;
	$combo_notification_mail->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/panel_decision_table_tdp.notification_mail.csv')) {
		$notification_mail_data = addslashes(implode('', @file(__DIR__ . '/hooks/panel_decision_table_tdp.notification_mail.csv')));
		$combo_notification_mail->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($notification_mail_data))));
		$combo_notification_mail->ListData = $combo_notification_mail->ListItem;
	} else {
		$combo_notification_mail->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Sent;;Not Sent;;Other"))));
		$combo_notification_mail->ListData = $combo_notification_mail->ListItem;
	}
	$combo_notification_mail->SelectName = 'notification_mail';

	if($hasSelectedId) {
		if(!($row = getRecord('panel_decision_table_tdp', $selectedId))) {
			return error_message($Translation['No records found'], 'panel_decision_table_tdp_view.php', false);
		}
		$combo_date_of_presentation->DefaultDate = $row['date_of_presentation'];
		$combo_notification_mail->SelectedData = $row['notification_mail'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_notification_mail->SelectedText = (isset($filterField[1]) && $filterField[1] == '17' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
	}
	$combo_notification_mail->Render();

	ob_start();
	?>

	<script>
		// initial lookup values

		$j(function() {
			setTimeout(function() {
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/panel_decision_table_tdp_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/panel_decision_table_tdp_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Panel decision table details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default ltr" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>',
				'<button
					type="submit"
					class="btn btn-default ltr"
					id="deselect"
					name="deselect_x"
					value="1"
					onclick="' . $backAction . '"
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#edition').replaceWith('<div class=\"form-control-static\" id=\"edition\">' + (\$j('#edition').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#project_id').replaceWith('<div class=\"form-control-static\" id=\"project_id\">' + (\$j('#project_id').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#date_of_presentation').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#date_of_presentationDay, #date_of_presentationMonth, #date_of_presentationYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#name_of_pi').replaceWith('<div class=\"form-control-static\" id=\"name_of_pi\">' + (\$j('#name_of_pi').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#mobile_number').replaceWith('<div class=\"form-control-static\" id=\"mobile_number\">' + (\$j('#mobile_number').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#institute').replaceWith('<div class=\"form-control-static\" id=\"institute\">' + (\$j('#institute').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#budget_specified').replaceWith('<div class=\"form-control-static\" id=\"budget_specified\">' + (\$j('#budget_specified').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#final_budget_to_be_allocated').replaceWith('<div class=\"form-control-static\" id=\"final_budget_to_be_allocated\">' + (\$j('#final_budget_to_be_allocated').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#experts_comments').replaceWith('<div class=\"form-control-static\" id=\"experts_comments\">' + (\$j('#experts_comments').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#trl').replaceWith('<div class=\"form-control-static\" id=\"trl\">' + (\$j('#trl').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#proposal_link').replaceWith('<div class=\"form-control-static\" id=\"proposal_link\">' + (\$j('#proposal_link').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#updated_proposal_link').replaceWith('<div class=\"form-control-static\" id=\"updated_proposal_link\">' + (\$j('#updated_proposal_link').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#where_budget_need').replaceWith('<div class=\"form-control-static\" id=\"where_budget_need\">' + (\$j('#where_budget_need').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#final_decision').replaceWith('<div class=\"form-control-static\" id=\"final_decision\">' + (\$j('#final_decision').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#notification_mail').replaceWith('<div class=\"form-control-static\" id=\"notification_mail\">' + (\$j('#notification_mail').val() || '') + '</div>'); \$j('#notification_mail-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#call_done').replaceWith('<div class=\"form-control-static\" id=\"call_done\">' + (\$j('#call_done').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace(
		'<%%COMBO(date_of_presentation)%%>',
		(!$fieldsAreEditable ?
			'<div class="form-control-static">' . $combo_date_of_presentation->GetHTML(true) . '</div>' :
			$combo_date_of_presentation->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(date_of_presentation)%%>', $combo_date_of_presentation->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(notification_mail)%%>', $combo_notification_mail->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(notification_mail)%%>', $combo_notification_mail->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = [];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(panel_decision_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(edition)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(project_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(date_of_presentation)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(project_title)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(name_of_pi)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(mobile_number)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(institute)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(budget_specified)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(final_budget_to_be_allocated)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(experts_comments)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(trl)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(proposal_link)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(updated_proposal_link)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(where_budget_need)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(final_decision)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(notification_mail)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(call_done)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_at)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_at)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_by_username)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_by_username)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		$templateCode = str_replace('<%%VALUE(panel_decision_id)%%>', safe_html($urow['panel_decision_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(panel_decision_id)%%>', urlencode($urow['panel_decision_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(edition)%%>', safe_html($urow['edition']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(edition)%%>', html_attr($row['edition']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(edition)%%>', urlencode($urow['edition']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(project_id)%%>', safe_html($urow['project_id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(project_id)%%>', html_attr($row['project_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(project_id)%%>', urlencode($urow['project_id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date_of_presentation)%%>', app_datetime($row['date_of_presentation']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date_of_presentation)%%>', urlencode(app_datetime($urow['date_of_presentation'])), $templateCode);
		if($fieldsAreEditable) {
			$templateCode = str_replace('<%%HTMLAREA(project_title)%%>', '<textarea maxlength="65500" name="project_title" id="project_title" rows="5">' . safe_html(htmlspecialchars_decode($row['project_title'])) . '</textarea>', $templateCode);
		} else {
			$templateCode = str_replace('<%%HTMLAREA(project_title)%%>', '<div id="project_title" class="form-control-static">' . $row['project_title'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(project_title)%%>', nl2br($row['project_title']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(project_title)%%>', urlencode($urow['project_title']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(name_of_pi)%%>', safe_html($urow['name_of_pi']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(name_of_pi)%%>', html_attr($row['name_of_pi']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(name_of_pi)%%>', urlencode($urow['name_of_pi']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(mobile_number)%%>', safe_html($urow['mobile_number']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(mobile_number)%%>', html_attr($row['mobile_number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(mobile_number)%%>', urlencode($urow['mobile_number']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(institute)%%>', safe_html($urow['institute']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(institute)%%>', html_attr($row['institute']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(institute)%%>', urlencode($urow['institute']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(budget_specified)%%>', safe_html($urow['budget_specified']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(budget_specified)%%>', html_attr($row['budget_specified']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(budget_specified)%%>', urlencode($urow['budget_specified']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(final_budget_to_be_allocated)%%>', safe_html($urow['final_budget_to_be_allocated']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(final_budget_to_be_allocated)%%>', html_attr($row['final_budget_to_be_allocated']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(final_budget_to_be_allocated)%%>', urlencode($urow['final_budget_to_be_allocated']), $templateCode);
		$templateCode = str_replace('<%%VALUE(experts_comments)%%>', safe_html($urow['experts_comments'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(experts_comments)%%>', urlencode($urow['experts_comments']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(trl)%%>', safe_html($urow['trl']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(trl)%%>', html_attr($row['trl']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(trl)%%>', urlencode($urow['trl']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(proposal_link)%%>', safe_html($urow['proposal_link']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(proposal_link)%%>', html_attr($row['proposal_link']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(proposal_link)%%>', urlencode($urow['proposal_link']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(updated_proposal_link)%%>', safe_html($urow['updated_proposal_link']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(updated_proposal_link)%%>', html_attr($row['updated_proposal_link']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(updated_proposal_link)%%>', urlencode($urow['updated_proposal_link']), $templateCode);
		$templateCode = str_replace('<%%VALUE(where_budget_need)%%>', safe_html($urow['where_budget_need'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(where_budget_need)%%>', urlencode($urow['where_budget_need']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(final_decision)%%>', safe_html($urow['final_decision']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(final_decision)%%>', html_attr($row['final_decision']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(final_decision)%%>', urlencode($urow['final_decision']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(notification_mail)%%>', safe_html($urow['notification_mail']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(notification_mail)%%>', html_attr($row['notification_mail']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(notification_mail)%%>', urlencode($urow['notification_mail']), $templateCode);
		$templateCode = str_replace('<%%VALUE(call_done)%%>', safe_html($urow['call_done'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(call_done)%%>', urlencode($urow['call_done']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', safe_html($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_at)%%>', safe_html($urow['created_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode($urow['created_at']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by)%%>', safe_html($urow['last_updated_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by)%%>', urlencode($urow['last_updated_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_at)%%>', safe_html($urow['last_updated_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_at)%%>', urlencode($urow['last_updated_at']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by_username)%%>', safe_html($urow['created_by_username']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by_username)%%>', urlencode($urow['created_by_username']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by_username)%%>', safe_html($urow['last_updated_by_username']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by_username)%%>', urlencode($urow['last_updated_by_username']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(panel_decision_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(panel_decision_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(edition)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(edition)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(project_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(project_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(date_of_presentation)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date_of_presentation)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(project_title)%%>', '<textarea maxlength="65500" name="project_title" id="project_title" rows="5"></textarea>', $templateCode);
		$templateCode = str_replace('<%%VALUE(name_of_pi)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(name_of_pi)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(mobile_number)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(mobile_number)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(institute)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(institute)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(budget_specified)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(budget_specified)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(final_budget_to_be_allocated)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(final_budget_to_be_allocated)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(experts_comments)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(experts_comments)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(trl)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(trl)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(proposal_link)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(proposal_link)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(updated_proposal_link)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(updated_proposal_link)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(where_budget_need)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(where_budget_need)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(final_decision)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(final_decision)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(notification_mail)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(notification_mail)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(call_done)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(call_done)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_at)%%>', '<%%creationDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode('<%%creationDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by)%%>', '<%%editorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by)%%>', urlencode('<%%editorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_at)%%>', '<%%editingDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_at)%%>', urlencode('<%%editingDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by_username)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by_username)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by_username)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by_username)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('panel_decision_table_tdp');
	if($hasSelectedId) {
		$jdata = get_joined_record('panel_decision_table_tdp', $selectedId);
		if($jdata === false) $jdata = get_defaults('panel_decision_table_tdp');
		$rdata = $row;
	}
	$templateCode .= loadView('panel_decision_table_tdp-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: panel_decision_table_tdp_dv
	if(function_exists('panel_decision_table_tdp_dv')) {
		$args = [];
		panel_decision_table_tdp_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}