<?php

// Data functions (insert, update, delete, form) for table payment_track_details_table

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function payment_track_details_table_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('payment_track_details_table');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'pfms_num' => Request::val('pfms_num', ''),
		'date' => Request::dateComponents('date', '1'),
		'description' => br2nl(Request::val('description', '')),
		'amount' => Request::val('amount', ''),
		'requested_by' => Request::val('requested_by', ''),
		'paid_to' => Request::val('paid_to', ''),
		'paid_status' => Request::val('paid_status', ''),
		'payment_date' => Request::dateComponents('payment_date', '1'),
		'remarks' => Request::val('remarks', ''),
		'upload_scanned_file_1' => Request::fileUpload('upload_scanned_file_1', [
			'maxSize' => 10240000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'success' => function($name, $selected_id) {
				Thumbnail::create($name, getThumbnailSpecs('payment_track_details_table', 'upload_scanned_file_1', 'tv'));
				Thumbnail::create($name, getThumbnailSpecs('payment_track_details_table', 'upload_scanned_file_1', 'dv'));
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('payment_track_details_table', 'upload_scanned_file_1', Request::val('SelectedID'));
			},
		]),
		'upload_scanned_file_2' => Request::fileUpload('upload_scanned_file_2', [
			'maxSize' => 10240000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'success' => function($name, $selected_id) {
				Thumbnail::create($name, getThumbnailSpecs('payment_track_details_table', 'upload_scanned_file_2', 'tv'));
				Thumbnail::create($name, getThumbnailSpecs('payment_track_details_table', 'upload_scanned_file_2', 'dv'));
			},
			'failure' => function($selected_id, $fileRemoved) {
				if(!strlen(Request::val('SelectedID'))) return '';

				/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
				return existing_value('payment_track_details_table', 'upload_scanned_file_2', Request::val('SelectedID'));
			},
		]),
		'created_by' => parseCode('<%%creatorUsername%%>', true),
		'created_at' => parseCode('<%%creationDateTime%%>', true),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('payment_track_details_table', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		payment_track_details_table_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function payment_track_details_table_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function payment_track_details_table_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('payment_track_details_table', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: payment_track_details_table_before_delete
	if(function_exists('payment_track_details_table_before_delete')) {
		$args = [];
		if(!payment_track_details_table_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: ''
			);
	}

	sql("DELETE FROM `payment_track_details_table` WHERE `payment_track_details_id`='{$selected_id}'", $eo);

	// hook: payment_track_details_table_after_delete
	if(function_exists('payment_track_details_table_after_delete')) {
		$args = [];
		payment_track_details_table_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='payment_track_details_table' AND `pkValue`='{$selected_id}'", $eo);
}

function payment_track_details_table_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('payment_track_details_table', $selected_id, 'edit')) return false;

	$data = [
		'pfms_num' => Request::val('pfms_num', ''),
		'date' => Request::dateComponents('date', ''),
		'description' => br2nl(Request::val('description', '')),
		'amount' => Request::val('amount', ''),
		'requested_by' => Request::val('requested_by', ''),
		'paid_to' => Request::val('paid_to', ''),
		'paid_status' => Request::val('paid_status', ''),
		'payment_date' => Request::dateComponents('payment_date', ''),
		'remarks' => Request::val('remarks', ''),
		'upload_scanned_file_1' => Request::fileUpload('upload_scanned_file_1', [
			'maxSize' => 10240000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
				Thumbnail::create($name, getThumbnailSpecs('payment_track_details_table', 'upload_scanned_file_1', 'tv'));
				Thumbnail::create($name, getThumbnailSpecs('payment_track_details_table', 'upload_scanned_file_1', 'dv'));
			},
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// do nothing: preserve removed files on server.
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('payment_track_details_table', 'upload_scanned_file_1', $selected_id);
			},
		]),
		'upload_scanned_file_2' => Request::fileUpload('upload_scanned_file_2', [
			'maxSize' => 10240000,
			'types' => 'jpg|jpeg|gif|png|webp',
			'noRename' => false,
			'dir' => '',
			'id' => $selected_id,
			'success' => function($name, $selected_id) {
				Thumbnail::create($name, getThumbnailSpecs('payment_track_details_table', 'upload_scanned_file_2', 'tv'));
				Thumbnail::create($name, getThumbnailSpecs('payment_track_details_table', 'upload_scanned_file_2', 'dv'));
			},
			'removeOnRequest' => true,
			'remove' => function($selected_id) {
				// do nothing: preserve removed files on server.
			},
			'failure' => function($selected_id, $fileRemoved) {
				if($fileRemoved) return '';
				return existing_value('payment_track_details_table', 'upload_scanned_file_2', $selected_id);
			},
		]),
		'last_updated_by' => parseCode('<%%editorUsername%%>', false),
		'last_updated_at' => parseCode('<%%editingDateTime%%>', false),
	];

	// get existing values
	$old_data = getRecord('payment_track_details_table', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: payment_track_details_table_before_update
	if(function_exists('payment_track_details_table_before_update')) {
		$args = ['old_data' => $old_data];
		if(!payment_track_details_table_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'payment_track_details_table',
		backtick_keys_once($set),
		['`payment_track_details_id`' => $selected_id],
		$error_message
	)) {
		echo $error_message;
		echo '<a href="payment_track_details_table_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	update_calc_fields('payment_track_details_table', $data['selectedID'], calculated_fields()['payment_track_details_table']);

	// hook: payment_track_details_table_after_update
	if(function_exists('payment_track_details_table_after_update')) {
		if($row = getRecord('payment_track_details_table', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['payment_track_details_id'];
		$args = ['old_data' => $old_data];
		if(!payment_track_details_table_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('payment_track_details_table', $selected_id);
}

function payment_track_details_table_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = true;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('payment_track_details_table');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('payment_track_details_table', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('payment_track_details_table', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('payment_track_details_table', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: date
	$combo_date = new DateCombo;
	$combo_date->DateFormat = "dmy";
	$combo_date->MinYear = defined('payment_track_details_table.date.MinYear') ? constant('payment_track_details_table.date.MinYear') : 1900;
	$combo_date->MaxYear = defined('payment_track_details_table.date.MaxYear') ? constant('payment_track_details_table.date.MaxYear') : 2100;
	$combo_date->DefaultDate = parseMySQLDate('1', '1');
	$combo_date->MonthNames = $Translation['month names'];
	$combo_date->NamePrefix = 'date';
	// combobox: paid_status
	$combo_paid_status = new Combo;
	$combo_paid_status->ListType = 0;
	$combo_paid_status->MultipleSeparator = ', ';
	$combo_paid_status->ListBoxHeight = 10;
	$combo_paid_status->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/payment_track_details_table.paid_status.csv')) {
		$paid_status_data = addslashes(implode('', @file(__DIR__ . '/hooks/payment_track_details_table.paid_status.csv')));
		$combo_paid_status->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($paid_status_data))));
		$combo_paid_status->ListData = $combo_paid_status->ListItem;
	} else {
		$combo_paid_status->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Yes;;No;;Pending;;Not Confirmed"))));
		$combo_paid_status->ListData = $combo_paid_status->ListItem;
	}
	$combo_paid_status->SelectName = 'paid_status';
	// combobox: payment_date
	$combo_payment_date = new DateCombo;
	$combo_payment_date->DateFormat = "dmy";
	$combo_payment_date->MinYear = defined('payment_track_details_table.payment_date.MinYear') ? constant('payment_track_details_table.payment_date.MinYear') : 1900;
	$combo_payment_date->MaxYear = defined('payment_track_details_table.payment_date.MaxYear') ? constant('payment_track_details_table.payment_date.MaxYear') : 2100;
	$combo_payment_date->DefaultDate = parseMySQLDate('1', '1');
	$combo_payment_date->MonthNames = $Translation['month names'];
	$combo_payment_date->NamePrefix = 'payment_date';

	if($hasSelectedId) {
		if(!($row = getRecord('payment_track_details_table', $selectedId))) {
			return error_message($Translation['No records found'], 'payment_track_details_table_view.php', false);
		}
		$combo_date->DefaultDate = $row['date'];
		$combo_paid_status->SelectedData = $row['paid_status'];
		$combo_payment_date->DefaultDate = $row['payment_date'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_paid_status->SelectedText = (isset($filterField[1]) && $filterField[1] == '8' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
	}
	$combo_paid_status->Render();

	ob_start();
	?>

	<script>
		// initial lookup values

		$j(function() {
			setTimeout(function() {
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/payment_track_details_table_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/payment_track_details_table_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Payment track details table details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default ltr" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>',
				'<button
					type="submit"
					class="btn btn-default ltr"
					id="deselect"
					name="deselect_x"
					value="1"
					onclick="' . $backAction . '"
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#pfms_num').replaceWith('<div class=\"form-control-static\" id=\"pfms_num\">' + (\$j('#pfms_num').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#date').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#dateDay, #dateMonth, #dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#description').replaceWith('<div class=\"form-control-static\" id=\"description\">' + (\$j('#description').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#amount').replaceWith('<div class=\"form-control-static\" id=\"amount\">' + (\$j('#amount').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#requested_by').replaceWith('<div class=\"form-control-static\" id=\"requested_by\">' + (\$j('#requested_by').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#paid_to').replaceWith('<div class=\"form-control-static\" id=\"paid_to\">' + (\$j('#paid_to').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#paid_status').replaceWith('<div class=\"form-control-static\" id=\"paid_status\">' + (\$j('#paid_status').val() || '') + '</div>'); \$j('#paid_status-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#payment_date').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#payment_dateDay, #payment_dateMonth, #payment_dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#upload_scanned_file_1').replaceWith('<div class=\"form-control-static\" id=\"upload_scanned_file_1\">' + (\$j('#upload_scanned_file_1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#upload_scanned_file_2').replaceWith('<div class=\"form-control-static\" id=\"upload_scanned_file_2\">' + (\$j('#upload_scanned_file_2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace(
		'<%%COMBO(date)%%>',
		(!$fieldsAreEditable ?
			'<div class="form-control-static">' . $combo_date->GetHTML(true) . '</div>' :
			$combo_date->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(date)%%>', $combo_date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(paid_status)%%>', $combo_paid_status->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(paid_status)%%>', $combo_paid_status->SelectedData, $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(payment_date)%%>',
		(!$fieldsAreEditable ?
			'<div class="form-control-static">' . $combo_payment_date->GetHTML(true) . '</div>' :
			$combo_payment_date->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(payment_date)%%>', $combo_payment_date->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = [];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(payment_track_details_id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(pfms_num)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(description)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(amount)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(requested_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(paid_to)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(paid_status)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(payment_date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(remarks)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(upload_scanned_file_1)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<input type="file" name="upload_scanned_file_1" id="upload_scanned_file_1" data-filetypes="jpg|jpeg|gif|png|webp" data-maxsize="10240000" style="max-width: calc(100% - 1.5rem);" accept="capture=camera,image/*">' . '<i class="text-danger clear-upload hidden pull-right" style="margin-top: -.1em; font-size: large;">&times;</i>'), $templateCode);
	if($allowUpdate && $row['upload_scanned_file_1'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(upload_scanned_file_1)%%>', '<input type="checkbox" name="upload_scanned_file_1_remove" id="upload_scanned_file_1_remove" value="1"> <label for="upload_scanned_file_1_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(upload_scanned_file_1)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(upload_scanned_file_2)%%>', ($noUploads ? '' : "<div>{$Translation['upload image']}</div>" . '<input type="file" name="upload_scanned_file_2" id="upload_scanned_file_2" data-filetypes="jpg|jpeg|gif|png|webp" data-maxsize="10240000" style="max-width: calc(100% - 1.5rem);" accept="capture=camera,image/*">' . '<i class="text-danger clear-upload hidden pull-right" style="margin-top: -.1em; font-size: large;">&times;</i>'), $templateCode);
	if($allowUpdate && $row['upload_scanned_file_2'] != '') {
		$templateCode = str_replace('<%%REMOVEFILE(upload_scanned_file_2)%%>', '<input type="checkbox" name="upload_scanned_file_2_remove" id="upload_scanned_file_2_remove" value="1"> <label for="upload_scanned_file_2_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	} else {
		$templateCode = str_replace('<%%REMOVEFILE(upload_scanned_file_2)%%>', '', $templateCode);
	}
	$templateCode = str_replace('<%%UPLOADFILE(created_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_at)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_at)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_by_username)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_by_username)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		$templateCode = str_replace('<%%VALUE(payment_track_details_id)%%>', safe_html($urow['payment_track_details_id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(payment_track_details_id)%%>', urlencode($urow['payment_track_details_id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(pfms_num)%%>', safe_html($urow['pfms_num']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(pfms_num)%%>', html_attr($row['pfms_num']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pfms_num)%%>', urlencode($urow['pfms_num']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', app_datetime($row['date']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode(app_datetime($urow['date'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(description)%%>', safe_html($urow['description'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(description)%%>', urlencode($urow['description']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(amount)%%>', safe_html($urow['amount']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(amount)%%>', html_attr($row['amount']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(amount)%%>', urlencode($urow['amount']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(requested_by)%%>', safe_html($urow['requested_by']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(requested_by)%%>', html_attr($row['requested_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(requested_by)%%>', urlencode($urow['requested_by']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(paid_to)%%>', safe_html($urow['paid_to']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(paid_to)%%>', html_attr($row['paid_to']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(paid_to)%%>', urlencode($urow['paid_to']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(paid_status)%%>', safe_html($urow['paid_status']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(paid_status)%%>', html_attr($row['paid_status']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(paid_status)%%>', urlencode($urow['paid_status']), $templateCode);
		$templateCode = str_replace('<%%VALUE(payment_date)%%>', app_datetime($row['payment_date']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(payment_date)%%>', urlencode(app_datetime($urow['payment_date'])), $templateCode);
		if($fieldsAreEditable) {
			$templateCode = str_replace('<%%HTMLAREA(remarks)%%>', '<textarea maxlength="65500" name="remarks" id="remarks" rows="5">' . safe_html(htmlspecialchars_decode($row['remarks'])) . '</textarea>', $templateCode);
		} else {
			$templateCode = str_replace('<%%HTMLAREA(remarks)%%>', '<div id="remarks" class="form-control-static">' . $row['remarks'] . '</div>', $templateCode);
		}
		$templateCode = str_replace('<%%VALUE(remarks)%%>', nl2br($row['remarks']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(remarks)%%>', urlencode($urow['remarks']), $templateCode);
		$row['upload_scanned_file_1'] = ($row['upload_scanned_file_1'] != '' ? $row['upload_scanned_file_1'] : 'blank.gif');
		if( $dvprint) $templateCode = str_replace('<%%VALUE(upload_scanned_file_1)%%>', safe_html($urow['upload_scanned_file_1']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(upload_scanned_file_1)%%>', html_attr($row['upload_scanned_file_1']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(upload_scanned_file_1)%%>', urlencode($urow['upload_scanned_file_1']), $templateCode);
		$row['upload_scanned_file_2'] = ($row['upload_scanned_file_2'] != '' ? $row['upload_scanned_file_2'] : 'blank.gif');
		if( $dvprint) $templateCode = str_replace('<%%VALUE(upload_scanned_file_2)%%>', safe_html($urow['upload_scanned_file_2']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(upload_scanned_file_2)%%>', html_attr($row['upload_scanned_file_2']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(upload_scanned_file_2)%%>', urlencode($urow['upload_scanned_file_2']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', safe_html($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_at)%%>', safe_html($urow['created_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode($urow['created_at']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by)%%>', safe_html($urow['last_updated_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by)%%>', urlencode($urow['last_updated_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_at)%%>', safe_html($urow['last_updated_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_at)%%>', urlencode($urow['last_updated_at']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by_username)%%>', safe_html($urow['created_by_username']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by_username)%%>', urlencode($urow['created_by_username']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by_username)%%>', safe_html($urow['last_updated_by_username']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by_username)%%>', urlencode($urow['last_updated_by_username']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(payment_track_details_id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(payment_track_details_id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(pfms_num)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pfms_num)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', '1', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode('1'), $templateCode);
		$templateCode = str_replace('<%%VALUE(description)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(description)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(amount)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(amount)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(requested_by)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(requested_by)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(paid_to)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(paid_to)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(paid_status)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(paid_status)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(payment_date)%%>', '1', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(payment_date)%%>', urlencode('1'), $templateCode);
		$templateCode = str_replace('<%%HTMLAREA(remarks)%%>', '<textarea maxlength="65500" name="remarks" id="remarks" rows="5"></textarea>', $templateCode);
		$templateCode = str_replace('<%%VALUE(upload_scanned_file_1)%%>', 'blank.gif', $templateCode);
		$templateCode = str_replace('<%%VALUE(upload_scanned_file_2)%%>', 'blank.gif', $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_at)%%>', '<%%creationDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode('<%%creationDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by)%%>', '<%%editorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by)%%>', urlencode('<%%editorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_at)%%>', '<%%editingDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_at)%%>', urlencode('<%%editingDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by_username)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by_username)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by_username)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by_username)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('payment_track_details_table');
	if($hasSelectedId) {
		$jdata = get_joined_record('payment_track_details_table', $selectedId);
		if($jdata === false) $jdata = get_defaults('payment_track_details_table');
		$rdata = $row;
	}
	$templateCode .= loadView('payment_track_details_table-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: payment_track_details_table_dv
	if(function_exists('payment_track_details_table_dv')) {
		$args = [];
		payment_track_details_table_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}