<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/problem_statement_table.php');
	include_once(__DIR__ . '/problem_statement_table_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('problem_statement_table');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'problem_statement_table';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`problem_statement_table`.`problem_statement_id`" => "problem_statement_id",
		"IF(    CHAR_LENGTH(`programs_table1`.`title_of_the_program`), CONCAT_WS('',   `programs_table1`.`title_of_the_program`), '') /* Select program id */" => "select_program_id",
		"`problem_statement_table`.`program_description`" => "program_description",
		"`problem_statement_table`.`remarks`" => "remarks",
		"`problem_statement_table`.`created_by`" => "created_by",
		"`problem_statement_table`.`created_at`" => "created_at",
		"`problem_statement_table`.`last_updated_by`" => "last_updated_by",
		"`problem_statement_table`.`last_updated_at`" => "last_updated_at",
		"`problem_statement_table`.`created_by_username`" => "created_by_username",
		"`problem_statement_table`.`last_updated_by_username`" => "last_updated_by_username",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`problem_statement_table`.`problem_statement_id`',
		2 => '`programs_table1`.`title_of_the_program`',
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`problem_statement_table`.`problem_statement_id`" => "problem_statement_id",
		"IF(    CHAR_LENGTH(`programs_table1`.`title_of_the_program`), CONCAT_WS('',   `programs_table1`.`title_of_the_program`), '') /* Select program id */" => "select_program_id",
		"`problem_statement_table`.`program_description`" => "program_description",
		"`problem_statement_table`.`remarks`" => "remarks",
		"`problem_statement_table`.`created_by`" => "created_by",
		"`problem_statement_table`.`created_at`" => "created_at",
		"`problem_statement_table`.`last_updated_by`" => "last_updated_by",
		"`problem_statement_table`.`last_updated_at`" => "last_updated_at",
		"`problem_statement_table`.`created_by_username`" => "created_by_username",
		"`problem_statement_table`.`last_updated_by_username`" => "last_updated_by_username",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`problem_statement_table`.`problem_statement_id`" => "ID",
		"IF(    CHAR_LENGTH(`programs_table1`.`title_of_the_program`), CONCAT_WS('',   `programs_table1`.`title_of_the_program`), '') /* Select program id */" => "Select program id",
		"`problem_statement_table`.`program_description`" => "Program description",
		"`problem_statement_table`.`remarks`" => "Remarks",
		"`problem_statement_table`.`created_by`" => "Created by",
		"`problem_statement_table`.`created_at`" => "Created at",
		"`problem_statement_table`.`last_updated_by`" => "Last updated by",
		"`problem_statement_table`.`last_updated_at`" => "Last updated at",
		"`problem_statement_table`.`created_by_username`" => "Created By Username",
		"`problem_statement_table`.`last_updated_by_username`" => "Last Updated by Username",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`problem_statement_table`.`problem_statement_id`" => "problem_statement_id",
		"IF(    CHAR_LENGTH(`programs_table1`.`title_of_the_program`), CONCAT_WS('',   `programs_table1`.`title_of_the_program`), '') /* Select program id */" => "select_program_id",
		"`problem_statement_table`.`program_description`" => "program_description",
		"`problem_statement_table`.`remarks`" => "remarks",
		"`problem_statement_table`.`created_by`" => "created_by",
		"`problem_statement_table`.`created_at`" => "created_at",
		"`problem_statement_table`.`last_updated_by`" => "last_updated_by",
		"`problem_statement_table`.`last_updated_at`" => "last_updated_at",
		"`problem_statement_table`.`created_by_username`" => "created_by_username",
		"`problem_statement_table`.`last_updated_by_username`" => "last_updated_by_username",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['select_program_id' => 'Select program id', ];

	$x->QueryFrom = "`problem_statement_table` LEFT JOIN `programs_table` as programs_table1 ON `programs_table1`.`programs_id`=`problem_statement_table`.`select_program_id` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'problem_statement_table_view.php';
	$x->TableTitle = 'Problem statement - App';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`problem_statement_table`.`problem_statement_id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Select program id', 'Program description', 'Remarks', 'Created by', 'Created at', 'Last updated by', 'Last updated at', 'Created By Username', 'Last Updated by Username', ];
	$x->ColFieldName = ['problem_statement_id', 'select_program_id', 'program_description', 'remarks', 'created_by', 'created_at', 'last_updated_by', 'last_updated_at', 'created_by_username', 'last_updated_by_username', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/problem_statement_table_templateTV.html';
	$x->SelectedTemplate = 'templates/problem_statement_table_templateTVS.html';
	$x->TemplateDV = 'templates/problem_statement_table_templateDV.html';
	$x->TemplateDVP = 'templates/problem_statement_table_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: problem_statement_table_init
	$render = true;
	if(function_exists('problem_statement_table_init')) {
		$args = [];
		$render = problem_statement_table_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: problem_statement_table_header
	$headerCode = '';
	if(function_exists('problem_statement_table_header')) {
		$args = [];
		$headerCode = problem_statement_table_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: problem_statement_table_footer
	$footerCode = '';
	if(function_exists('problem_statement_table_footer')) {
		$args = [];
		$footerCode = problem_statement_table_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
