<?php

// Data functions (insert, update, delete, form) for table school_list

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function school_list_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('school_list');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'username' => parseCode('<%%creatorUsername%%>', true),
		'district_name' => Request::val('district_name', ''),
		'school_code' => Request::val('school_code', ''),
		'school_name' => Request::val('school_name', ''),
		'pincode' => Request::val('pincode', ''),
		'school_type' => Request::val('school_type', ''),
		'school_phone_number' => Request::val('school_phone_number', ''),
		'created_by' => parseCode('<%%creatorUsername%%>', true),
		'created_at' => parseCode('<%%creationDateTime%%>', true),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('school_list', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		school_list_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function school_list_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function school_list_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('school_list', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: school_list_before_delete
	if(function_exists('school_list_before_delete')) {
		$args = [];
		if(!school_list_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: ''
			);
	}

	sql("DELETE FROM `school_list` WHERE `id`='{$selected_id}'", $eo);

	// hook: school_list_after_delete
	if(function_exists('school_list_after_delete')) {
		$args = [];
		school_list_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='school_list' AND `pkValue`='{$selected_id}'", $eo);
}

function school_list_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('school_list', $selected_id, 'edit')) return false;

	$data = [
		'district_name' => Request::val('district_name', ''),
		'school_code' => Request::val('school_code', ''),
		'school_name' => Request::val('school_name', ''),
		'pincode' => Request::val('pincode', ''),
		'school_type' => Request::val('school_type', ''),
		'school_phone_number' => Request::val('school_phone_number', ''),
		'last_updated_by' => parseCode('<%%editorUsername%%>', false),
		'last_updated_at' => parseCode('<%%editingDateTime%%>', false),
	];

	// get existing values
	$old_data = getRecord('school_list', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: school_list_before_update
	if(function_exists('school_list_before_update')) {
		$args = ['old_data' => $old_data];
		if(!school_list_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'school_list',
		backtick_keys_once($set),
		['`id`' => $selected_id],
		$error_message
	)) {
		echo $error_message;
		echo '<a href="school_list_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	update_calc_fields('school_list', $data['selectedID'], calculated_fields()['school_list']);

	// hook: school_list_after_update
	if(function_exists('school_list_after_update')) {
		if($row = getRecord('school_list', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!school_list_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('school_list', $selected_id);
}

function school_list_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = true;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('school_list');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('school_list', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('school_list', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('school_list', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	if($hasSelectedId) {
		if(!($row = getRecord('school_list', $selectedId))) {
			return error_message($Translation['No records found'], 'school_list_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
	}

	ob_start();
	?>

	<script>
		// initial lookup values

		$j(function() {
			setTimeout(function() {
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/school_list_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/school_list_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Projects of startpnt and chanakya table details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default ltr" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>',
				'<button
					type="submit"
					class="btn btn-default ltr"
					id="deselect"
					name="deselect_x"
					value="1"
					onclick="' . $backAction . '"
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#district_name').replaceWith('<div class=\"form-control-static\" id=\"district_name\">' + (\$j('#district_name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#school_code').replaceWith('<div class=\"form-control-static\" id=\"school_code\">' + (\$j('#school_code').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#school_name').replaceWith('<div class=\"form-control-static\" id=\"school_name\">' + (\$j('#school_name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#pincode').replaceWith('<div class=\"form-control-static\" id=\"pincode\">' + (\$j('#pincode').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#school_type').replaceWith('<div class=\"form-control-static\" id=\"school_type\">' + (\$j('#school_type').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#school_phone_number').replaceWith('<div class=\"form-control-static\" id=\"school_phone_number\">' + (\$j('#school_phone_number').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = [];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(username)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(district_name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(school_code)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(school_name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(pincode)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(school_type)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(school_phone_number)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_by_username)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_at)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_by_username)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_at)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		$templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(username)%%>', safe_html($urow['username']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(username)%%>', urlencode($urow['username']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(district_name)%%>', safe_html($urow['district_name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(district_name)%%>', html_attr($row['district_name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(district_name)%%>', urlencode($urow['district_name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(school_code)%%>', safe_html($urow['school_code']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(school_code)%%>', html_attr($row['school_code']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(school_code)%%>', urlencode($urow['school_code']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(school_name)%%>', safe_html($urow['school_name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(school_name)%%>', html_attr($row['school_name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(school_name)%%>', urlencode($urow['school_name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(pincode)%%>', safe_html($urow['pincode']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(pincode)%%>', html_attr($row['pincode']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pincode)%%>', urlencode($urow['pincode']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(school_type)%%>', safe_html($urow['school_type']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(school_type)%%>', html_attr($row['school_type']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(school_type)%%>', urlencode($urow['school_type']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(school_phone_number)%%>', safe_html($urow['school_phone_number']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(school_phone_number)%%>', html_attr($row['school_phone_number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(school_phone_number)%%>', urlencode($urow['school_phone_number']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', safe_html($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by)%%>', safe_html($urow['last_updated_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by)%%>', urlencode($urow['last_updated_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by_username)%%>', safe_html($urow['created_by_username']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by_username)%%>', urlencode($urow['created_by_username']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_at)%%>', safe_html($urow['created_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode($urow['created_at']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by_username)%%>', safe_html($urow['last_updated_by_username']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by_username)%%>', urlencode($urow['last_updated_by_username']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_at)%%>', safe_html($urow['last_updated_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_at)%%>', urlencode($urow['last_updated_at']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(username)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(username)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(district_name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(district_name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(school_code)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(school_code)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(school_name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(school_name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(pincode)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(pincode)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(school_type)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(school_type)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(school_phone_number)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(school_phone_number)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by)%%>', '<%%editorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by)%%>', urlencode('<%%editorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by_username)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by_username)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_at)%%>', '<%%creationDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode('<%%creationDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by_username)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by_username)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_at)%%>', '<%%editingDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_at)%%>', urlencode('<%%editingDateTime%%>'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('school_list');
	if($hasSelectedId) {
		$jdata = get_joined_record('school_list', $selectedId);
		if($jdata === false) $jdata = get_defaults('school_list');
		$rdata = $row;
	}
	$templateCode .= loadView('school_list-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: school_list_dv
	if(function_exists('school_list_dv')) {
		$args = [];
		school_list_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}