<?php

// Data functions (insert, update, delete, form) for table shortlisted_startups_for_fund_table

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function shortlisted_startups_for_fund_table_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('shortlisted_startups_for_fund_table');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	$data = [
		'startup' => Request::lookup('startup', ''),
		'scheme' => Request::val('scheme', ''),
		'recommended_fund' => Request::val('recommended_fund', ''),
		'name_of_founder' => Request::val('name_of_founder', ''),
		'email_of_founder' => Request::val('email_of_founder', ''),
		'phone_number_of_founder' => Request::val('phone_number_of_founder', ''),
		'due_diligence_start' => Request::val('due_diligence_start', ''),
		'terms_agreed' => Request::val('terms_agreed', ''),
		'grant_amount' => Request::val('grant_amount', ''),
		'debt_amount' => Request::val('debt_amount', ''),
		'ocd_or_ccd_amount' => Request::val('ocd_or_ccd_amount', ''),
		'equity_amount' => Request::val('equity_amount', ''),
		'interest_rate' => Request::val('interest_rate', ''),
		'period' => Request::val('period', ''),
		'conversion_formula' => Request::val('conversion_formula', ''),
		'equity_diluted' => Request::val('equity_diluted', ''),
		'comments' => br2nl(Request::val('comments', '')),
		'remarks_1' => br2nl(Request::val('remarks_1', '')),
		'remarks_2' => br2nl(Request::val('remarks_2', '')),
		'created_by' => parseCode('<%%creatorUsername%%>', true),
		'created_at' => parseCode('<%%creationDateTime%%>', true),
	];

	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('shortlisted_startups_for_fund_table', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		shortlisted_startups_for_fund_table_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function shortlisted_startups_for_fund_table_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function shortlisted_startups_for_fund_table_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('shortlisted_startups_for_fund_table', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: shortlisted_startups_for_fund_table_before_delete
	if(function_exists('shortlisted_startups_for_fund_table_before_delete')) {
		$args = [];
		if(!shortlisted_startups_for_fund_table_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: ''
			);
	}

	sql("DELETE FROM `shortlisted_startups_for_fund_table` WHERE `id`='{$selected_id}'", $eo);

	// hook: shortlisted_startups_for_fund_table_after_delete
	if(function_exists('shortlisted_startups_for_fund_table_after_delete')) {
		$args = [];
		shortlisted_startups_for_fund_table_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='shortlisted_startups_for_fund_table' AND `pkValue`='{$selected_id}'", $eo);
}

function shortlisted_startups_for_fund_table_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('shortlisted_startups_for_fund_table', $selected_id, 'edit')) return false;

	$data = [
		'startup' => Request::lookup('startup', ''),
		'scheme' => Request::val('scheme', ''),
		'recommended_fund' => Request::val('recommended_fund', ''),
		'name_of_founder' => Request::val('name_of_founder', ''),
		'email_of_founder' => Request::val('email_of_founder', ''),
		'phone_number_of_founder' => Request::val('phone_number_of_founder', ''),
		'due_diligence_start' => Request::val('due_diligence_start', ''),
		'terms_agreed' => Request::val('terms_agreed', ''),
		'grant_amount' => Request::val('grant_amount', ''),
		'debt_amount' => Request::val('debt_amount', ''),
		'ocd_or_ccd_amount' => Request::val('ocd_or_ccd_amount', ''),
		'equity_amount' => Request::val('equity_amount', ''),
		'interest_rate' => Request::val('interest_rate', ''),
		'period' => Request::val('period', ''),
		'conversion_formula' => Request::val('conversion_formula', ''),
		'equity_diluted' => Request::val('equity_diluted', ''),
		'comments' => br2nl(Request::val('comments', '')),
		'remarks_1' => br2nl(Request::val('remarks_1', '')),
		'remarks_2' => br2nl(Request::val('remarks_2', '')),
		'last_updated_by' => parseCode('<%%editorUsername%%>', false),
		'last_updated_at' => parseCode('<%%editingDateTime%%>', false),
	];

	// get existing values
	$old_data = getRecord('shortlisted_startups_for_fund_table', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: shortlisted_startups_for_fund_table_before_update
	if(function_exists('shortlisted_startups_for_fund_table_before_update')) {
		$args = ['old_data' => $old_data];
		if(!shortlisted_startups_for_fund_table_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'shortlisted_startups_for_fund_table',
		backtick_keys_once($set),
		['`id`' => $selected_id],
		$error_message
	)) {
		echo $error_message;
		echo '<a href="shortlisted_startups_for_fund_table_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	update_calc_fields('shortlisted_startups_for_fund_table', $data['selectedID'], calculated_fields()['shortlisted_startups_for_fund_table']);

	// hook: shortlisted_startups_for_fund_table_after_update
	if(function_exists('shortlisted_startups_for_fund_table_after_update')) {
		if($row = getRecord('shortlisted_startups_for_fund_table', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!shortlisted_startups_for_fund_table_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('shortlisted_startups_for_fund_table', $selected_id);
}

function shortlisted_startups_for_fund_table_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = true;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('shortlisted_startups_for_fund_table');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('shortlisted_startups_for_fund_table', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('shortlisted_startups_for_fund_table', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('shortlisted_startups_for_fund_table', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);

	$filterer_startup = Request::val('filterer_startup');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: startup
	$combo_startup = new DataCombo;
	// combobox: scheme
	$combo_scheme = new Combo;
	$combo_scheme->ListType = 0;
	$combo_scheme->MultipleSeparator = ', ';
	$combo_scheme->ListBoxHeight = 10;
	$combo_scheme->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/shortlisted_startups_for_fund_table.scheme.csv')) {
		$scheme_data = addslashes(implode('', @file(__DIR__ . '/hooks/shortlisted_startups_for_fund_table.scheme.csv')));
		$combo_scheme->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($scheme_data))));
		$combo_scheme->ListData = $combo_scheme->ListItem;
	} else {
		$combo_scheme->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Discover;;SMART GIS;;SARADHI;;VIKAS;;PRAYAS"))));
		$combo_scheme->ListData = $combo_scheme->ListItem;
	}
	$combo_scheme->SelectName = 'scheme';

	if($hasSelectedId) {
		if(!($row = getRecord('shortlisted_startups_for_fund_table', $selectedId))) {
			return error_message($Translation['No records found'], 'shortlisted_startups_for_fund_table_view.php', false);
		}
		$combo_startup->SelectedData = $row['startup'];
		$combo_scheme->SelectedData = $row['scheme'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_startup->SelectedData = $filterer_startup;
		$combo_scheme->SelectedText = (isset($filterField[1]) && $filterField[1] == '3' && $filterOperator[1] == '<=>' ? $filterValue[1] : entitiesToUTF8(''));
	}
	$combo_startup->HTML = '<span id="startup-container' . $rnd1 . '"></span><input type="hidden" name="startup" id="startup' . $rnd1 . '" value="' . html_attr($combo_startup->SelectedData) . '">';
	$combo_startup->MatchText = '<span id="startup-container-readonly' . $rnd1 . '"></span><input type="hidden" name="startup" id="startup' . $rnd1 . '" value="' . html_attr($combo_startup->SelectedData) . '">';
	$combo_scheme->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_startup__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['startup'] : htmlspecialchars($filterer_startup, ENT_QUOTES)); ?>"};

		$j(function() {
			setTimeout(function() {
				if(typeof(startup_reload__RAND__) == 'function') startup_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function startup_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#startup-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_startup__RAND__.value, t: 'shortlisted_startups_for_fund_table', f: 'startup' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="startup"]').val(resp.results[0].id);
							$j('[id=startup-container-readonly__RAND__]').html('<span class="match-text" id="startup-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=all_startup_data_table_view_parent]').hide(); } else { $j('.btn[id=all_startup_data_table_view_parent]').show(); }


							if(typeof(startup_update_autofills__RAND__) == 'function') startup_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'shortlisted_startups_for_fund_table', f: 'startup' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_startup__RAND__.value = e.added.id;
				AppGini.current_startup__RAND__.text = e.added.text;
				$j('[name="startup"]').val(e.added.id);
				$j(this).parents('.form-group')
					.find('.btn[id=all_startup_data_table_view_parent]')
					.toggleClass('hidden', e.added.id == '<?php echo empty_lookup_value; ?>');


				if(typeof(startup_update_autofills__RAND__) == 'function') startup_update_autofills__RAND__();
			});

			if(!$j("#startup-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_startup__RAND__.value, t: 'shortlisted_startups_for_fund_table', f: 'startup' },
					success: function(resp) {
						$j('[name="startup"]').val(resp.results[0].id);
						$j('[id=startup-container-readonly__RAND__]').html('<span class="match-text" id="startup-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=all_startup_data_table_view_parent]').hide(); } else { $j('.btn[id=all_startup_data_table_view_parent]').show(); }

						if(typeof(startup_update_autofills__RAND__) == 'function') startup_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_startup__RAND__.value, t: 'shortlisted_startups_for_fund_table', f: 'startup' },
				success: function(resp) {
					$j('[id=startup-container__RAND__], [id=startup-container-readonly__RAND__]').html('<span class="match-text" id="startup-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=all_startup_data_table_view_parent]').hide(); } else { $j('.btn[id=all_startup_data_table_view_parent]').show(); }

					if(typeof(startup_update_autofills__RAND__) == 'function') startup_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/shortlisted_startups_for_fund_table_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/shortlisted_startups_for_fund_table_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Shortlisted startups for fund table details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default ltr" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>',
				'<button
					type="submit"
					class="btn btn-default ltr"
					id="deselect"
					name="deselect_x"
					value="1"
					onclick="' . $backAction . '"
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#startup').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#startup_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\t\$j('#scheme').replaceWith('<div class=\"form-control-static\" id=\"scheme\">' + (\$j('#scheme').val() || '') + '</div>'); \$j('#scheme-multi-selection-help').hide();\n";
		$jsReadOnly .= "\t\$j('#recommended_fund').replaceWith('<div class=\"form-control-static\" id=\"recommended_fund\">' + (\$j('#recommended_fund').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#name_of_founder').replaceWith('<div class=\"form-control-static\" id=\"name_of_founder\">' + (\$j('#name_of_founder').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#email_of_founder').replaceWith('<div class=\"form-control-static\" id=\"email_of_founder\">' + (\$j('#email_of_founder').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#phone_number_of_founder').replaceWith('<div class=\"form-control-static\" id=\"phone_number_of_founder\">' + (\$j('#phone_number_of_founder').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#due_diligence_start').replaceWith('<div class=\"form-control-static\" id=\"due_diligence_start\">' + (\$j('#due_diligence_start').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#terms_agreed').replaceWith('<div class=\"form-control-static\" id=\"terms_agreed\">' + (\$j('#terms_agreed').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#grant_amount').replaceWith('<div class=\"form-control-static\" id=\"grant_amount\">' + (\$j('#grant_amount').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#debt_amount').replaceWith('<div class=\"form-control-static\" id=\"debt_amount\">' + (\$j('#debt_amount').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#ocd_or_ccd_amount').replaceWith('<div class=\"form-control-static\" id=\"ocd_or_ccd_amount\">' + (\$j('#ocd_or_ccd_amount').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#equity_amount').replaceWith('<div class=\"form-control-static\" id=\"equity_amount\">' + (\$j('#equity_amount').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#interest_rate').replaceWith('<div class=\"form-control-static\" id=\"interest_rate\">' + (\$j('#interest_rate').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#period').replaceWith('<div class=\"form-control-static\" id=\"period\">' + (\$j('#period').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#conversion_formula').replaceWith('<div class=\"form-control-static\" id=\"conversion_formula\">' + (\$j('#conversion_formula').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#equity_diluted').replaceWith('<div class=\"form-control-static\" id=\"equity_diluted\">' + (\$j('#equity_diluted').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#comments').replaceWith('<div class=\"form-control-static\" id=\"comments\">' + (\$j('#comments').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#remarks_1').replaceWith('<div class=\"form-control-static\" id=\"remarks_1\">' + (\$j('#remarks_1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#remarks_2').replaceWith('<div class=\"form-control-static\" id=\"remarks_2\">' + (\$j('#remarks_2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(startup)%%>', $combo_startup->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(startup)%%>', $combo_startup->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(startup)%%>', urlencode($combo_startup->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(scheme)%%>', $combo_scheme->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(scheme)%%>', $combo_scheme->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['startup' => ['all_startup_data_table', 'Select startup'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(startup)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(scheme)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(recommended_fund)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(name_of_founder)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(email_of_founder)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(phone_number_of_founder)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(due_diligence_start)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(terms_agreed)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(grant_amount)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(debt_amount)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ocd_or_ccd_amount)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(equity_amount)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(interest_rate)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(period)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(conversion_formula)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(equity_diluted)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(comments)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(remarks_1)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(remarks_2)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_at)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_at)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_by_username)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_by_username)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		$templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(startup)%%>', safe_html($urow['startup']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(startup)%%>', html_attr($row['startup']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(startup)%%>', urlencode($urow['startup']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(scheme)%%>', safe_html($urow['scheme']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(scheme)%%>', html_attr($row['scheme']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(scheme)%%>', urlencode($urow['scheme']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(recommended_fund)%%>', safe_html($urow['recommended_fund']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(recommended_fund)%%>', html_attr($row['recommended_fund']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(recommended_fund)%%>', urlencode($urow['recommended_fund']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(name_of_founder)%%>', safe_html($urow['name_of_founder']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(name_of_founder)%%>', html_attr($row['name_of_founder']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(name_of_founder)%%>', urlencode($urow['name_of_founder']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(email_of_founder)%%>', safe_html($urow['email_of_founder']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(email_of_founder)%%>', html_attr($row['email_of_founder']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email_of_founder)%%>', urlencode($urow['email_of_founder']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(phone_number_of_founder)%%>', safe_html($urow['phone_number_of_founder']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(phone_number_of_founder)%%>', html_attr($row['phone_number_of_founder']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(phone_number_of_founder)%%>', urlencode($urow['phone_number_of_founder']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(due_diligence_start)%%>', safe_html($urow['due_diligence_start']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(due_diligence_start)%%>', html_attr($row['due_diligence_start']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(due_diligence_start)%%>', urlencode($urow['due_diligence_start']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(terms_agreed)%%>', safe_html($urow['terms_agreed']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(terms_agreed)%%>', html_attr($row['terms_agreed']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(terms_agreed)%%>', urlencode($urow['terms_agreed']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(grant_amount)%%>', safe_html($urow['grant_amount']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(grant_amount)%%>', html_attr($row['grant_amount']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(grant_amount)%%>', urlencode($urow['grant_amount']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(debt_amount)%%>', safe_html($urow['debt_amount']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(debt_amount)%%>', html_attr($row['debt_amount']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(debt_amount)%%>', urlencode($urow['debt_amount']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ocd_or_ccd_amount)%%>', safe_html($urow['ocd_or_ccd_amount']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ocd_or_ccd_amount)%%>', html_attr($row['ocd_or_ccd_amount']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ocd_or_ccd_amount)%%>', urlencode($urow['ocd_or_ccd_amount']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(equity_amount)%%>', safe_html($urow['equity_amount']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(equity_amount)%%>', html_attr($row['equity_amount']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(equity_amount)%%>', urlencode($urow['equity_amount']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(interest_rate)%%>', safe_html($urow['interest_rate']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(interest_rate)%%>', html_attr($row['interest_rate']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(interest_rate)%%>', urlencode($urow['interest_rate']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(period)%%>', safe_html($urow['period']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(period)%%>', html_attr($row['period']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(period)%%>', urlencode($urow['period']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(conversion_formula)%%>', safe_html($urow['conversion_formula']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(conversion_formula)%%>', html_attr($row['conversion_formula']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(conversion_formula)%%>', urlencode($urow['conversion_formula']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(equity_diluted)%%>', safe_html($urow['equity_diluted']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(equity_diluted)%%>', html_attr($row['equity_diluted']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(equity_diluted)%%>', urlencode($urow['equity_diluted']), $templateCode);
		$templateCode = str_replace('<%%VALUE(comments)%%>', safe_html($urow['comments'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(comments)%%>', urlencode($urow['comments']), $templateCode);
		$templateCode = str_replace('<%%VALUE(remarks_1)%%>', safe_html($urow['remarks_1'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(remarks_1)%%>', urlencode($urow['remarks_1']), $templateCode);
		$templateCode = str_replace('<%%VALUE(remarks_2)%%>', safe_html($urow['remarks_2'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(remarks_2)%%>', urlencode($urow['remarks_2']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', safe_html($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_at)%%>', safe_html($urow['created_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode($urow['created_at']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by)%%>', safe_html($urow['last_updated_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by)%%>', urlencode($urow['last_updated_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_at)%%>', safe_html($urow['last_updated_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_at)%%>', urlencode($urow['last_updated_at']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by_username)%%>', safe_html($urow['created_by_username']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by_username)%%>', urlencode($urow['created_by_username']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by_username)%%>', safe_html($urow['last_updated_by_username']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by_username)%%>', urlencode($urow['last_updated_by_username']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(startup)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(startup)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(scheme)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(scheme)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(recommended_fund)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(recommended_fund)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(name_of_founder)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(name_of_founder)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(email_of_founder)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(email_of_founder)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(phone_number_of_founder)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(phone_number_of_founder)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(due_diligence_start)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(due_diligence_start)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(terms_agreed)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(terms_agreed)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(grant_amount)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(grant_amount)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(debt_amount)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(debt_amount)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ocd_or_ccd_amount)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ocd_or_ccd_amount)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(equity_amount)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(equity_amount)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(interest_rate)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(interest_rate)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(period)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(period)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(conversion_formula)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(conversion_formula)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(equity_diluted)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(equity_diluted)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(comments)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(comments)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(remarks_1)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(remarks_1)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(remarks_2)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(remarks_2)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_at)%%>', '<%%creationDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode('<%%creationDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by)%%>', '<%%editorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by)%%>', urlencode('<%%editorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_at)%%>', '<%%editingDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_at)%%>', urlencode('<%%editingDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by_username)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by_username)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by_username)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by_username)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('shortlisted_startups_for_fund_table');
	if($hasSelectedId) {
		$jdata = get_joined_record('shortlisted_startups_for_fund_table', $selectedId);
		if($jdata === false) $jdata = get_defaults('shortlisted_startups_for_fund_table');
		$rdata = $row;
	}
	$templateCode .= loadView('shortlisted_startups_for_fund_table-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: shortlisted_startups_for_fund_table_dv
	if(function_exists('shortlisted_startups_for_fund_table_dv')) {
		$args = [];
		shortlisted_startups_for_fund_table_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}