<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/task_setting_table.php');
	include_once(__DIR__ . '/task_setting_table_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('task_setting_table');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'task_setting_table';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`task_setting_table`.`task_id`" => "task_id",
		"`task_setting_table`.`task_status`" => "task_status",
		"`task_setting_table`.`task_description`" => "task_description",
		"`task_setting_table`.`task_duration`" => "task_duration",
		"if(`task_setting_table`.`task_set_date`,date_format(`task_setting_table`.`task_set_date`,'%d/%m/%Y'),'')" => "task_set_date",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Supervisor name */" => "supervisor_name",
		"IF(    CHAR_LENGTH(`user_table2`.`memberID`) || CHAR_LENGTH(`user_table2`.`name`), CONCAT_WS('',   `user_table2`.`memberID`, '::', `user_table2`.`name`), '') /* Assigned to */" => "assigned_to",
		"`task_setting_table`.`task_setting_str`" => "task_setting_str",
		"`task_setting_table`.`last_updated_by`" => "last_updated_by",
		"`task_setting_table`.`last_updated_at`" => "last_updated_at",
		"`task_setting_table`.`created_by`" => "created_by",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`task_setting_table`.`task_id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`task_setting_table`.`task_set_date`',
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`task_setting_table`.`task_id`" => "task_id",
		"`task_setting_table`.`task_status`" => "task_status",
		"`task_setting_table`.`task_description`" => "task_description",
		"`task_setting_table`.`task_duration`" => "task_duration",
		"if(`task_setting_table`.`task_set_date`,date_format(`task_setting_table`.`task_set_date`,'%d/%m/%Y'),'')" => "task_set_date",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Supervisor name */" => "supervisor_name",
		"IF(    CHAR_LENGTH(`user_table2`.`memberID`) || CHAR_LENGTH(`user_table2`.`name`), CONCAT_WS('',   `user_table2`.`memberID`, '::', `user_table2`.`name`), '') /* Assigned to */" => "assigned_to",
		"`task_setting_table`.`task_setting_str`" => "task_setting_str",
		"`task_setting_table`.`last_updated_by`" => "last_updated_by",
		"`task_setting_table`.`last_updated_at`" => "last_updated_at",
		"`task_setting_table`.`created_by`" => "created_by",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`task_setting_table`.`task_id`" => "ID",
		"`task_setting_table`.`task_status`" => "Task status",
		"`task_setting_table`.`task_description`" => "Task description",
		"`task_setting_table`.`task_duration`" => "Task duration",
		"`task_setting_table`.`task_set_date`" => "Task set date",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Supervisor name */" => "Supervisor name",
		"IF(    CHAR_LENGTH(`user_table2`.`memberID`) || CHAR_LENGTH(`user_table2`.`name`), CONCAT_WS('',   `user_table2`.`memberID`, '::', `user_table2`.`name`), '') /* Assigned to */" => "Assigned to",
		"`task_setting_table`.`task_setting_str`" => "Task setting str",
		"`task_setting_table`.`last_updated_by`" => "Last updated by",
		"`task_setting_table`.`last_updated_at`" => "Last updated at",
		"`task_setting_table`.`created_by`" => "Created By",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`task_setting_table`.`task_id`" => "task_id",
		"`task_setting_table`.`task_status`" => "task_status",
		"`task_setting_table`.`task_description`" => "task_description",
		"`task_setting_table`.`task_duration`" => "task_duration",
		"if(`task_setting_table`.`task_set_date`,date_format(`task_setting_table`.`task_set_date`,'%d/%m/%Y'),'')" => "task_set_date",
		"IF(    CHAR_LENGTH(`user_table1`.`memberID`) || CHAR_LENGTH(`user_table1`.`name`), CONCAT_WS('',   `user_table1`.`memberID`, '::', `user_table1`.`name`), '') /* Supervisor name */" => "supervisor_name",
		"IF(    CHAR_LENGTH(`user_table2`.`memberID`) || CHAR_LENGTH(`user_table2`.`name`), CONCAT_WS('',   `user_table2`.`memberID`, '::', `user_table2`.`name`), '') /* Assigned to */" => "assigned_to",
		"`task_setting_table`.`task_setting_str`" => "task_setting_str",
		"`task_setting_table`.`last_updated_by`" => "last_updated_by",
		"`task_setting_table`.`last_updated_at`" => "last_updated_at",
		"`task_setting_table`.`created_by`" => "created_by",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['supervisor_name' => 'Supervisor name', 'assigned_to' => 'Assigned to', ];

	$x->QueryFrom = "`task_setting_table` LEFT JOIN `user_table` as user_table1 ON `user_table1`.`user_id`=`task_setting_table`.`supervisor_name` LEFT JOIN `user_table` as user_table2 ON `user_table2`.`user_id`=`task_setting_table`.`assigned_to` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'task_setting_table_view.php';
	$x->TableTitle = 'Task setting - App';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`task_setting_table`.`task_id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Task status', 'Task description', 'Task duration', 'Task set date', 'Supervisor name', 'Assigned to', 'Last updated by', 'Last updated at', 'Created By', ];
	$x->ColFieldName = ['task_id', 'task_status', 'task_description', 'task_duration', 'task_set_date', 'supervisor_name', 'assigned_to', 'last_updated_by', 'last_updated_at', 'created_by', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 9, 10, 11, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/task_setting_table_templateTV.html';
	$x->SelectedTemplate = 'templates/task_setting_table_templateTVS.html';
	$x->TemplateDV = 'templates/task_setting_table_templateDV.html';
	$x->TemplateDVP = 'templates/task_setting_table_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: task_setting_table_init
	$render = true;
	if(function_exists('task_setting_table_init')) {
		$args = [];
		$render = task_setting_table_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: task_setting_table_header
	$headerCode = '';
	if(function_exists('task_setting_table_header')) {
		$args = [];
		$headerCode = task_setting_table_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: task_setting_table_footer
	$footerCode = '';
	if(function_exists('task_setting_table_footer')) {
		$args = [];
		$footerCode = task_setting_table_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
