<?php
// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/training_program_on_geospatial_tchnologies_table.php');
	include_once(__DIR__ . '/training_program_on_geospatial_tchnologies_table_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('training_program_on_geospatial_tchnologies_table');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'training_program_on_geospatial_tchnologies_table';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`training_program_on_geospatial_tchnologies_table`.`id`" => "id",
		"`training_program_on_geospatial_tchnologies_table`.`username`" => "username",
		"`training_program_on_geospatial_tchnologies_table`.`certificate_number`" => "certificate_number",
		"if(`training_program_on_geospatial_tchnologies_table`.`datetime`,date_format(`training_program_on_geospatial_tchnologies_table`.`datetime`,'%d/%m/%Y'),'')" => "datetime",
		"`training_program_on_geospatial_tchnologies_table`.`salutation`" => "salutation",
		"`training_program_on_geospatial_tchnologies_table`.`name`" => "name",
		"`training_program_on_geospatial_tchnologies_table`.`email_id`" => "email_id",
		"`training_program_on_geospatial_tchnologies_table`.`secondary_email_id`" => "secondary_email_id",
		"`training_program_on_geospatial_tchnologies_table`.`mobile_number`" => "mobile_number",
		"`training_program_on_geospatial_tchnologies_table`.`whatsapp_number`" => "whatsapp_number",
		"`training_program_on_geospatial_tchnologies_table`.`gender`" => "gender",
		"`training_program_on_geospatial_tchnologies_table`.`social_media_link`" => "social_media_link",
		"`training_program_on_geospatial_tchnologies_table`.`education_qualification`" => "education_qualification",
		"`training_program_on_geospatial_tchnologies_table`.`profession`" => "profession",
		"`training_program_on_geospatial_tchnologies_table`.`school_name`" => "school_name",
		"`training_program_on_geospatial_tchnologies_table`.`parents_name`" => "parents_name",
		"`training_program_on_geospatial_tchnologies_table`.`parents_contact_number`" => "parents_contact_number",
		"`training_program_on_geospatial_tchnologies_table`.`parents_email_id`" => "parents_email_id",
		"`training_program_on_geospatial_tchnologies_table`.`residential_address`" => "residential_address",
		"`training_program_on_geospatial_tchnologies_table`.`parents_designation`" => "parents_designation",
		"`training_program_on_geospatial_tchnologies_table`.`parents_school_name`" => "parents_school_name",
		"`training_program_on_geospatial_tchnologies_table`.`teaching_subject`" => "teaching_subject",
		"`training_program_on_geospatial_tchnologies_table`.`address_line_2`" => "address_line_2",
		"`training_program_on_geospatial_tchnologies_table`.`city`" => "city",
		"`training_program_on_geospatial_tchnologies_table`.`state_region_province`" => "state_region_province",
		"`training_program_on_geospatial_tchnologies_table`.`zip_code`" => "zip_code",
		"`training_program_on_geospatial_tchnologies_table`.`country`" => "country",
		"`training_program_on_geospatial_tchnologies_table`.`how_did_you_know`" => "how_did_you_know",
		"`training_program_on_geospatial_tchnologies_table`.`attended_training_school`" => "attended_training_school",
		"if(`training_program_on_geospatial_tchnologies_table`.`attended_training_date`,date_format(`training_program_on_geospatial_tchnologies_table`.`attended_training_date`,'%d/%m/%Y'),'')" => "attended_training_date",
		"`training_program_on_geospatial_tchnologies_table`.`created_by`" => "created_by",
		"`training_program_on_geospatial_tchnologies_table`.`last_updated_by`" => "last_updated_by",
		"`training_program_on_geospatial_tchnologies_table`.`created_by_username`" => "created_by_username",
		"`training_program_on_geospatial_tchnologies_table`.`created_at`" => "created_at",
		"`training_program_on_geospatial_tchnologies_table`.`last_updated_by_username`" => "last_updated_by_username",
		"`training_program_on_geospatial_tchnologies_table`.`last_updated_at`" => "last_updated_at",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`training_program_on_geospatial_tchnologies_table`.`id`',
		2 => 2,
		3 => 3,
		4 => '`training_program_on_geospatial_tchnologies_table`.`datetime`',
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11,
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19,
		20 => 20,
		21 => 21,
		22 => 22,
		23 => 23,
		24 => 24,
		25 => 25,
		26 => 26,
		27 => 27,
		28 => 28,
		29 => 29,
		30 => '`training_program_on_geospatial_tchnologies_table`.`attended_training_date`',
		31 => 31,
		32 => 32,
		33 => 33,
		34 => 34,
		35 => 35,
		36 => 36,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`training_program_on_geospatial_tchnologies_table`.`id`" => "id",
		"`training_program_on_geospatial_tchnologies_table`.`username`" => "username",
		"`training_program_on_geospatial_tchnologies_table`.`certificate_number`" => "certificate_number",
		"if(`training_program_on_geospatial_tchnologies_table`.`datetime`,date_format(`training_program_on_geospatial_tchnologies_table`.`datetime`,'%d/%m/%Y'),'')" => "datetime",
		"`training_program_on_geospatial_tchnologies_table`.`salutation`" => "salutation",
		"`training_program_on_geospatial_tchnologies_table`.`name`" => "name",
		"`training_program_on_geospatial_tchnologies_table`.`email_id`" => "email_id",
		"`training_program_on_geospatial_tchnologies_table`.`secondary_email_id`" => "secondary_email_id",
		"`training_program_on_geospatial_tchnologies_table`.`mobile_number`" => "mobile_number",
		"`training_program_on_geospatial_tchnologies_table`.`whatsapp_number`" => "whatsapp_number",
		"`training_program_on_geospatial_tchnologies_table`.`gender`" => "gender",
		"`training_program_on_geospatial_tchnologies_table`.`social_media_link`" => "social_media_link",
		"`training_program_on_geospatial_tchnologies_table`.`education_qualification`" => "education_qualification",
		"`training_program_on_geospatial_tchnologies_table`.`profession`" => "profession",
		"`training_program_on_geospatial_tchnologies_table`.`school_name`" => "school_name",
		"`training_program_on_geospatial_tchnologies_table`.`parents_name`" => "parents_name",
		"`training_program_on_geospatial_tchnologies_table`.`parents_contact_number`" => "parents_contact_number",
		"`training_program_on_geospatial_tchnologies_table`.`parents_email_id`" => "parents_email_id",
		"`training_program_on_geospatial_tchnologies_table`.`residential_address`" => "residential_address",
		"`training_program_on_geospatial_tchnologies_table`.`parents_designation`" => "parents_designation",
		"`training_program_on_geospatial_tchnologies_table`.`parents_school_name`" => "parents_school_name",
		"`training_program_on_geospatial_tchnologies_table`.`teaching_subject`" => "teaching_subject",
		"`training_program_on_geospatial_tchnologies_table`.`address_line_2`" => "address_line_2",
		"`training_program_on_geospatial_tchnologies_table`.`city`" => "city",
		"`training_program_on_geospatial_tchnologies_table`.`state_region_province`" => "state_region_province",
		"`training_program_on_geospatial_tchnologies_table`.`zip_code`" => "zip_code",
		"`training_program_on_geospatial_tchnologies_table`.`country`" => "country",
		"`training_program_on_geospatial_tchnologies_table`.`how_did_you_know`" => "how_did_you_know",
		"`training_program_on_geospatial_tchnologies_table`.`attended_training_school`" => "attended_training_school",
		"if(`training_program_on_geospatial_tchnologies_table`.`attended_training_date`,date_format(`training_program_on_geospatial_tchnologies_table`.`attended_training_date`,'%d/%m/%Y'),'')" => "attended_training_date",
		"`training_program_on_geospatial_tchnologies_table`.`created_by`" => "created_by",
		"`training_program_on_geospatial_tchnologies_table`.`last_updated_by`" => "last_updated_by",
		"`training_program_on_geospatial_tchnologies_table`.`created_by_username`" => "created_by_username",
		"`training_program_on_geospatial_tchnologies_table`.`created_at`" => "created_at",
		"`training_program_on_geospatial_tchnologies_table`.`last_updated_by_username`" => "last_updated_by_username",
		"`training_program_on_geospatial_tchnologies_table`.`last_updated_at`" => "last_updated_at",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`training_program_on_geospatial_tchnologies_table`.`id`" => "ID",
		"`training_program_on_geospatial_tchnologies_table`.`username`" => "Username",
		"`training_program_on_geospatial_tchnologies_table`.`certificate_number`" => "Certificate No.",
		"`training_program_on_geospatial_tchnologies_table`.`datetime`" => "Datetime",
		"`training_program_on_geospatial_tchnologies_table`.`salutation`" => "Salutation",
		"`training_program_on_geospatial_tchnologies_table`.`name`" => "Name",
		"`training_program_on_geospatial_tchnologies_table`.`email_id`" => "Email id",
		"`training_program_on_geospatial_tchnologies_table`.`secondary_email_id`" => "Secondary email id",
		"`training_program_on_geospatial_tchnologies_table`.`mobile_number`" => "Mobile number",
		"`training_program_on_geospatial_tchnologies_table`.`whatsapp_number`" => "Whatsapp number",
		"`training_program_on_geospatial_tchnologies_table`.`gender`" => "Gender",
		"`training_program_on_geospatial_tchnologies_table`.`social_media_link`" => "Social media link",
		"`training_program_on_geospatial_tchnologies_table`.`education_qualification`" => "Educational Qualification",
		"`training_program_on_geospatial_tchnologies_table`.`profession`" => "Profession",
		"`training_program_on_geospatial_tchnologies_table`.`school_name`" => "School/Institute Name",
		"`training_program_on_geospatial_tchnologies_table`.`parents_name`" => "Parent\'s Name",
		"`training_program_on_geospatial_tchnologies_table`.`parents_contact_number`" => "Parent\'s Contact No.",
		"`training_program_on_geospatial_tchnologies_table`.`parents_email_id`" => "Parents email id",
		"`training_program_on_geospatial_tchnologies_table`.`residential_address`" => "Residential address",
		"`training_program_on_geospatial_tchnologies_table`.`parents_designation`" => "Designation",
		"`training_program_on_geospatial_tchnologies_table`.`parents_school_name`" => "Parents school name",
		"`training_program_on_geospatial_tchnologies_table`.`teaching_subject`" => "Teaching subject",
		"`training_program_on_geospatial_tchnologies_table`.`address_line_2`" => "Address line 2",
		"`training_program_on_geospatial_tchnologies_table`.`city`" => "City",
		"`training_program_on_geospatial_tchnologies_table`.`state_region_province`" => "State/Region/Province",
		"`training_program_on_geospatial_tchnologies_table`.`zip_code`" => "Zip code",
		"`training_program_on_geospatial_tchnologies_table`.`country`" => "Country",
		"`training_program_on_geospatial_tchnologies_table`.`how_did_you_know`" => "How did you know about the Training/Workshop?",
		"`training_program_on_geospatial_tchnologies_table`.`attended_training_school`" => "Training/Workshop attended at school/Institute name.",
		"`training_program_on_geospatial_tchnologies_table`.`attended_training_date`" => "Attended training date",
		"`training_program_on_geospatial_tchnologies_table`.`created_by`" => "Created By",
		"`training_program_on_geospatial_tchnologies_table`.`last_updated_by`" => "Last Updated By",
		"`training_program_on_geospatial_tchnologies_table`.`created_by_username`" => "Created By Username",
		"`training_program_on_geospatial_tchnologies_table`.`created_at`" => "Created At",
		"`training_program_on_geospatial_tchnologies_table`.`last_updated_by_username`" => "Last Updated by Username",
		"`training_program_on_geospatial_tchnologies_table`.`last_updated_at`" => "Last Updated At",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`training_program_on_geospatial_tchnologies_table`.`id`" => "id",
		"`training_program_on_geospatial_tchnologies_table`.`username`" => "username",
		"`training_program_on_geospatial_tchnologies_table`.`certificate_number`" => "certificate_number",
		"if(`training_program_on_geospatial_tchnologies_table`.`datetime`,date_format(`training_program_on_geospatial_tchnologies_table`.`datetime`,'%d/%m/%Y'),'')" => "datetime",
		"`training_program_on_geospatial_tchnologies_table`.`salutation`" => "salutation",
		"`training_program_on_geospatial_tchnologies_table`.`name`" => "name",
		"`training_program_on_geospatial_tchnologies_table`.`email_id`" => "email_id",
		"`training_program_on_geospatial_tchnologies_table`.`secondary_email_id`" => "secondary_email_id",
		"`training_program_on_geospatial_tchnologies_table`.`mobile_number`" => "mobile_number",
		"`training_program_on_geospatial_tchnologies_table`.`whatsapp_number`" => "whatsapp_number",
		"`training_program_on_geospatial_tchnologies_table`.`gender`" => "gender",
		"`training_program_on_geospatial_tchnologies_table`.`social_media_link`" => "social_media_link",
		"`training_program_on_geospatial_tchnologies_table`.`education_qualification`" => "education_qualification",
		"`training_program_on_geospatial_tchnologies_table`.`profession`" => "profession",
		"`training_program_on_geospatial_tchnologies_table`.`school_name`" => "school_name",
		"`training_program_on_geospatial_tchnologies_table`.`parents_name`" => "parents_name",
		"`training_program_on_geospatial_tchnologies_table`.`parents_contact_number`" => "parents_contact_number",
		"`training_program_on_geospatial_tchnologies_table`.`parents_email_id`" => "parents_email_id",
		"`training_program_on_geospatial_tchnologies_table`.`residential_address`" => "residential_address",
		"`training_program_on_geospatial_tchnologies_table`.`parents_designation`" => "parents_designation",
		"`training_program_on_geospatial_tchnologies_table`.`parents_school_name`" => "parents_school_name",
		"`training_program_on_geospatial_tchnologies_table`.`teaching_subject`" => "teaching_subject",
		"`training_program_on_geospatial_tchnologies_table`.`address_line_2`" => "address_line_2",
		"`training_program_on_geospatial_tchnologies_table`.`city`" => "city",
		"`training_program_on_geospatial_tchnologies_table`.`state_region_province`" => "state_region_province",
		"`training_program_on_geospatial_tchnologies_table`.`zip_code`" => "zip_code",
		"`training_program_on_geospatial_tchnologies_table`.`country`" => "country",
		"`training_program_on_geospatial_tchnologies_table`.`how_did_you_know`" => "how_did_you_know",
		"`training_program_on_geospatial_tchnologies_table`.`attended_training_school`" => "attended_training_school",
		"if(`training_program_on_geospatial_tchnologies_table`.`attended_training_date`,date_format(`training_program_on_geospatial_tchnologies_table`.`attended_training_date`,'%d/%m/%Y'),'')" => "attended_training_date",
		"`training_program_on_geospatial_tchnologies_table`.`created_by`" => "created_by",
		"`training_program_on_geospatial_tchnologies_table`.`last_updated_by`" => "last_updated_by",
		"`training_program_on_geospatial_tchnologies_table`.`created_by_username`" => "created_by_username",
		"`training_program_on_geospatial_tchnologies_table`.`created_at`" => "created_at",
		"`training_program_on_geospatial_tchnologies_table`.`last_updated_by_username`" => "last_updated_by_username",
		"`training_program_on_geospatial_tchnologies_table`.`last_updated_at`" => "last_updated_at",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`training_program_on_geospatial_tchnologies_table` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->AllowAdminShowSQL = showSQL();
	$x->RecordsPerPage = 100;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'training_program_on_geospatial_tchnologies_table_view.php';
	$x->TableTitle = 'Training Program on Geospatial Technologies Details - App';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`training_program_on_geospatial_tchnologies_table`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Certificate No.', 'Datetime', 'Salutation', 'Name', 'Email id', 'Secondary email id', 'Mobile number', 'Whatsapp number', 'Gender', 'Social media link', 'Educational Qualification', 'Profession', 'School/Institute Name', 'Parent\'s Name', 'Parent\'s Contact No.', 'Parents email id', 'Residential address', 'Designation', 'Parents school name', 'Teaching subject', 'Address line 2', 'City', 'State/Region/Province', 'Zip code', 'Country', 'How did you know about the Training/Workshop?', 'Training/Workshop attended at school/Institute name.', 'Attended training date', 'Created By', 'Last Updated By', 'Created By Username', 'Created At', 'Last Updated by Username', 'Last Updated At', ];
	$x->ColFieldName = ['id', 'certificate_number', 'datetime', 'salutation', 'name', 'email_id', 'secondary_email_id', 'mobile_number', 'whatsapp_number', 'gender', 'social_media_link', 'education_qualification', 'profession', 'school_name', 'parents_name', 'parents_contact_number', 'parents_email_id', 'residential_address', 'parents_designation', 'parents_school_name', 'teaching_subject', 'address_line_2', 'city', 'state_region_province', 'zip_code', 'country', 'how_did_you_know', 'attended_training_school', 'attended_training_date', 'created_by', 'last_updated_by', 'created_by_username', 'created_at', 'last_updated_by_username', 'last_updated_at', ];
	$x->ColNumber  = [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/training_program_on_geospatial_tchnologies_table_templateTV.html';
	$x->SelectedTemplate = 'templates/training_program_on_geospatial_tchnologies_table_templateTVS.html';
	$x->TemplateDV = 'templates/training_program_on_geospatial_tchnologies_table_templateDV.html';
	$x->TemplateDVP = 'templates/training_program_on_geospatial_tchnologies_table_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: training_program_on_geospatial_tchnologies_table_init
	$render = true;
	if(function_exists('training_program_on_geospatial_tchnologies_table_init')) {
		$args = [];
		$render = training_program_on_geospatial_tchnologies_table_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: training_program_on_geospatial_tchnologies_table_header
	$headerCode = '';
	if(function_exists('training_program_on_geospatial_tchnologies_table_header')) {
		$args = [];
		$headerCode = training_program_on_geospatial_tchnologies_table_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: training_program_on_geospatial_tchnologies_table_footer
	$footerCode = '';
	if(function_exists('training_program_on_geospatial_tchnologies_table_footer')) {
		$args = [];
		$footerCode = training_program_on_geospatial_tchnologies_table_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php');
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
