<?php

// Data functions (insert, update, delete, form) for table travel_stay_table

// This script and data application was generated by AppGini, https://bigprof.com/appgini
// Download AppGini for free from https://bigprof.com/appgini/download/

function travel_stay_table_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('travel_stay_table');
	if(!$arrPerm['insert']) {
		$error_message = $Translation['no insert permission'];
		return false;
	}

	// automatic travel_details if passed as filterer
	if(Request::val('filterer_travel_details')) {
		$_REQUEST['travel_details'] = Request::val('filterer_travel_details');
	}

	$data = [
		'hotel_name' => Request::val('hotel_name', ''),
		'destination_city' => Request::val('destination_city', ''),
		'checkin_date' => Request::dateComponents('checkin_date', ''),
		'checkout_date' => Request::dateComponents('checkout_date', ''),
		'room_preferance' => Request::val('room_preferance', ''),
		'remarks' => br2nl(Request::val('remarks', '')),
		'created_by' => parseCode('<%%creatorUsername%%>', true),
		'created_at' => parseCode('<%%creationDateTime%%>', true),
	];


	// automatic travel_details if passed as filterer
	if(Request::val('filterer_travel_details')) {
		$data['travel_details'] = Request::val('filterer_travel_details');
	}
	// record owner is current user
	$recordOwner = getLoggedMemberID();

	$recID = tableInsert('travel_stay_table', $data, $recordOwner, $error_message);

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID')) && $recID !== false)
		travel_stay_table_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function travel_stay_table_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);
	$currentUsername = getLoggedMemberID();
	$errorMessage = '';

	// launch requests, asynchronously
	curl_batch($requests);
}

function travel_stay_table_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('travel_stay_table', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: travel_stay_table_before_delete
	if(function_exists('travel_stay_table_before_delete')) {
		$args = [];
		if(!travel_stay_table_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `travel_stay_table` WHERE `id`='{$selected_id}'", $eo);

	// hook: travel_stay_table_after_delete
	if(function_exists('travel_stay_table_after_delete')) {
		$args = [];
		travel_stay_table_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='travel_stay_table' AND `pkValue`='{$selected_id}'", $eo);
}

function travel_stay_table_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('travel_stay_table', $selected_id, 'edit')) return false;

	$data = [
		'hotel_name' => Request::val('hotel_name', ''),
		'destination_city' => Request::val('destination_city', ''),
		'checkin_date' => Request::dateComponents('checkin_date', ''),
		'checkout_date' => Request::dateComponents('checkout_date', ''),
		'room_preferance' => Request::val('room_preferance', ''),
		'remarks' => br2nl(Request::val('remarks', '')),
		'last_updated_by' => parseCode('<%%editorUsername%%>', false),
		'last_updated_at' => parseCode('<%%editingDateTime%%>', false),
	];

	// get existing values
	$old_data = getRecord('travel_stay_table', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: travel_stay_table_before_update
	if(function_exists('travel_stay_table_before_update')) {
		$args = ['old_data' => $old_data];
		if(!travel_stay_table_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'travel_stay_table', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="travel_stay_table_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	update_calc_fields('travel_stay_table', $data['selectedID'], calculated_fields()['travel_stay_table']);

	// hook: travel_stay_table_after_update
	if(function_exists('travel_stay_table_after_update')) {
		if($row = getRecord('travel_stay_table', $data['selectedID'])) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!travel_stay_table_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update record update timestamp
	set_record_owner('travel_stay_table', $selected_id);
}

function travel_stay_table_form($selectedId = '', $allowUpdate = true, $allowInsert = true, $allowDelete = true, $separateDV = true, $templateDV = '', $templateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selectedId. If $selectedId
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = $row = $urow = $jsReadOnly = $jsEditable = $lookups = null;
	$noSaveAsCopy = false;
	$hasSelectedId = strlen($selectedId) > 0;

	// mm: get table permissions
	$arrPerm = getTablePermissions('travel_stay_table');
	$allowInsert = ($arrPerm['insert'] ? true : false);
	$allowUpdate = $hasSelectedId && check_record_permission('travel_stay_table', $selectedId, 'edit');
	$allowDelete = $hasSelectedId && check_record_permission('travel_stay_table', $selectedId, 'delete');

	if(!$allowInsert && !$hasSelectedId)
		// no insert permission and no record selected
		// so show access denied error -- except if TVDV: just hide DV
		return $separateDV ? $Translation['tableAccessDenied'] : '';

	if($hasSelectedId && !check_record_permission('travel_stay_table', $selectedId, 'view'))
		return $Translation['tableAccessDenied'];

	// print preview?
	$dvprint = $hasSelectedId && Request::val('dvprint_x') != '';

	$showSaveNew = !$dvprint && ($allowInsert && !$hasSelectedId);
	$showSaveChanges = !$dvprint && $allowUpdate && $hasSelectedId;
	$showDelete = !$dvprint && $allowDelete && $hasSelectedId;
	$showSaveAsCopy = !$dvprint && ($allowInsert && $hasSelectedId && !$noSaveAsCopy);
	$fieldsAreEditable = !$dvprint && (($allowInsert && !$hasSelectedId) || ($allowUpdate && $hasSelectedId) || $showSaveAsCopy);

	$filterer_travel_details = Request::val('filterer_travel_details');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: travel_details
	$combo_travel_details = new DataCombo;
	// combobox: checkin_date
	$combo_checkin_date = new DateCombo;
	$combo_checkin_date->DateFormat = "dmy";
	$combo_checkin_date->MinYear = defined('travel_stay_table.checkin_date.MinYear') ? constant('travel_stay_table.checkin_date.MinYear') : 1900;
	$combo_checkin_date->MaxYear = defined('travel_stay_table.checkin_date.MaxYear') ? constant('travel_stay_table.checkin_date.MaxYear') : 2100;
	$combo_checkin_date->DefaultDate = parseMySQLDate('', '');
	$combo_checkin_date->MonthNames = $Translation['month names'];
	$combo_checkin_date->NamePrefix = 'checkin_date';
	// combobox: checkout_date
	$combo_checkout_date = new DateCombo;
	$combo_checkout_date->DateFormat = "dmy";
	$combo_checkout_date->MinYear = defined('travel_stay_table.checkout_date.MinYear') ? constant('travel_stay_table.checkout_date.MinYear') : 1900;
	$combo_checkout_date->MaxYear = defined('travel_stay_table.checkout_date.MaxYear') ? constant('travel_stay_table.checkout_date.MaxYear') : 2100;
	$combo_checkout_date->DefaultDate = parseMySQLDate('', '');
	$combo_checkout_date->MonthNames = $Translation['month names'];
	$combo_checkout_date->NamePrefix = 'checkout_date';

	if($hasSelectedId) {
		if(!($row = getRecord('travel_stay_table', $selectedId))) {
			return error_message($Translation['No records found'], 'travel_stay_table_view.php', false);
		}
		$combo_travel_details->SelectedData = $row['travel_details'];
		$combo_checkin_date->DefaultDate = $row['checkin_date'];
		$combo_checkout_date->DefaultDate = $row['checkout_date'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_travel_details->SelectedData = $filterer_travel_details;
	}
	$combo_travel_details->HTML = '<span id="travel_details-container' . $rnd1 . '"></span><input type="hidden" name="travel_details" id="travel_details' . $rnd1 . '" value="' . html_attr($combo_travel_details->SelectedData) . '">';
	$combo_travel_details->MatchText = '<span id="travel_details-container-readonly' . $rnd1 . '"></span><input type="hidden" name="travel_details" id="travel_details' . $rnd1 . '" value="' . html_attr($combo_travel_details->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_travel_details__RAND__ = { text: "", value: "<?php echo addslashes($hasSelectedId ? $urow['travel_details'] : htmlspecialchars($filterer_travel_details, ENT_QUOTES)); ?>"};

		$j(function() {
			setTimeout(function() {
				if(typeof(travel_details_reload__RAND__) == 'function') travel_details_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function travel_details_reload__RAND__() {
		<?php if($fieldsAreEditable) { ?>

			$j("#travel_details-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_travel_details__RAND__.value, t: 'travel_stay_table', f: 'travel_details' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="travel_details"]').val(resp.results[0].id);
							$j('[id=travel_details-container-readonly__RAND__]').html('<span class="match-text" id="travel_details-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=travel_table_view_parent]').hide(); } else { $j('.btn[id=travel_table_view_parent]').show(); }


							if(typeof(travel_details_update_autofills__RAND__) == 'function') travel_details_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'travel_stay_table', f: 'travel_details' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_travel_details__RAND__.value = e.added.id;
				AppGini.current_travel_details__RAND__.text = e.added.text;
				$j('[name="travel_details"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=travel_table_view_parent]').hide(); } else { $j('.btn[id=travel_table_view_parent]').show(); }


				if(typeof(travel_details_update_autofills__RAND__) == 'function') travel_details_update_autofills__RAND__();
			});

			if(!$j("#travel_details-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_travel_details__RAND__.value, t: 'travel_stay_table', f: 'travel_details' },
					success: function(resp) {
						$j('[name="travel_details"]').val(resp.results[0].id);
						$j('[id=travel_details-container-readonly__RAND__]').html('<span class="match-text" id="travel_details-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=travel_table_view_parent]').hide(); } else { $j('.btn[id=travel_table_view_parent]').show(); }

						if(typeof(travel_details_update_autofills__RAND__) == 'function') travel_details_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_travel_details__RAND__.value, t: 'travel_stay_table', f: 'travel_details' },
				success: function(resp) {
					$j('[id=travel_details-container__RAND__], [id=travel_details-container-readonly__RAND__]').html('<span class="match-text" id="travel_details-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=travel_table_view_parent]').hide(); } else { $j('.btn[id=travel_table_view_parent]').show(); }

					if(typeof(travel_details_update_autofills__RAND__) == 'function') travel_details_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$templateDVP}") ? "./{$templateDVP}" : './templates/travel_stay_table_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$templateDV}") ? "./{$templateDV}" : './templates/travel_stay_table_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Travel hotel table details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($showSaveNew) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
	} elseif($showSaveAsCopy) {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = 'return true;';
	}

	if($hasSelectedId) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($allowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($allowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$allowInsert
			&& !$allowUpdate && !$allowDelete && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(!$fieldsAreEditable) {
		$jsReadOnly = '';
		$jsReadOnly .= "\t\$j('#hotel_name').replaceWith('<div class=\"form-control-static\" id=\"hotel_name\">' + (\$j('#hotel_name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#destination_city').replaceWith('<div class=\"form-control-static\" id=\"destination_city\">' + (\$j('#destination_city').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#checkin_date').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#checkin_dateDay, #checkin_dateMonth, #checkin_dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#checkout_date').prop('readonly', true);\n";
		$jsReadOnly .= "\t\$j('#checkout_dateDay, #checkout_dateMonth, #checkout_dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\t\$j('#room_preferance').replaceWith('<div class=\"form-control-static\" id=\"room_preferance\">' + (\$j('#room_preferance').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('#remarks').replaceWith('<div class=\"form-control-static\" id=\"remarks\">' + (\$j('#remarks').val() || '') + '</div>');\n";
		$jsReadOnly .= "\t\$j('.select2-container').hide();\n";

		$noUploads = true;
	} else {
		// temporarily disable form change handler till time and datetime pickers are enabled
		$jsEditable = "\t\$j('form').eq(0).data('already_changed', true);";
		$jsEditable .= "\t\$j('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(travel_details)%%>', $combo_travel_details->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(travel_details)%%>', $combo_travel_details->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(travel_details)%%>', urlencode($combo_travel_details->MatchText), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(checkin_date)%%>', 
		(!$fieldsAreEditable ? 
			'<div class="form-control-static">' . $combo_checkin_date->GetHTML(true) . '</div>' : 
			$combo_checkin_date->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(checkin_date)%%>', $combo_checkin_date->GetHTML(true), $templateCode);
	$templateCode = str_replace(
		'<%%COMBO(checkout_date)%%>', 
		(!$fieldsAreEditable ? 
			'<div class="form-control-static">' . $combo_checkout_date->GetHTML(true) . '</div>' : 
			$combo_checkout_date->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(checkout_date)%%>', $combo_checkout_date->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['travel_details' => ['travel_table', 'Travel details'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if(($pt_perm['view'] && isDetailViewEnabled($ptfc[0])) || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(travel_details)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(hotel_name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(destination_city)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(checkin_date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(checkout_date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(room_preferance)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(remarks)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(created_at)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_by)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(last_updated_at)%%>', '', $templateCode);

	// process values
	if($hasSelectedId) {
		$templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(travel_details)%%>', safe_html($urow['travel_details']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(travel_details)%%>', urlencode($urow['travel_details']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(hotel_name)%%>', safe_html($urow['hotel_name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(hotel_name)%%>', html_attr($row['hotel_name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hotel_name)%%>', urlencode($urow['hotel_name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(destination_city)%%>', safe_html($urow['destination_city']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(destination_city)%%>', html_attr($row['destination_city']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(destination_city)%%>', urlencode($urow['destination_city']), $templateCode);
		$templateCode = str_replace('<%%VALUE(checkin_date)%%>', app_datetime($row['checkin_date']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(checkin_date)%%>', urlencode(app_datetime($urow['checkin_date'])), $templateCode);
		$templateCode = str_replace('<%%VALUE(checkout_date)%%>', app_datetime($row['checkout_date']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(checkout_date)%%>', urlencode(app_datetime($urow['checkout_date'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(room_preferance)%%>', safe_html($urow['room_preferance']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(room_preferance)%%>', html_attr($row['room_preferance']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(room_preferance)%%>', urlencode($urow['room_preferance']), $templateCode);
		$templateCode = str_replace('<%%VALUE(remarks)%%>', safe_html($urow['remarks'], $fieldsAreEditable), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(remarks)%%>', urlencode($urow['remarks']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', safe_html($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode($urow['created_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_at)%%>', safe_html($urow['created_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode($urow['created_at']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by)%%>', safe_html($urow['last_updated_by']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by)%%>', urlencode($urow['last_updated_by']), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_at)%%>', safe_html($urow['last_updated_at']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_at)%%>', urlencode($urow['last_updated_at']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(travel_details)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(travel_details)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(hotel_name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(hotel_name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(destination_city)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(destination_city)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(checkin_date)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(checkin_date)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(checkout_date)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(checkout_date)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(room_preferance)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(room_preferance)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(remarks)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(remarks)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_by)%%>', '<%%creatorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_by)%%>', urlencode('<%%creatorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(created_at)%%>', '<%%creationDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(created_at)%%>', urlencode('<%%creationDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_by)%%>', '<%%editorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_by)%%>', urlencode('<%%editorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(last_updated_at)%%>', '<%%editingDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(last_updated_at)%%>', urlencode('<%%editingDateTime%%>'), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$hasSelectedId) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');
	if(isset($filterField[1]) && $filterField[1] == '2' && $filterOperator[1] == '<=>')
		$templateCode.="\n<input type=hidden name=travel_details value=\"" . html_attr($filterValue[1]) . "\">\n";

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('travel_stay_table');
	if($hasSelectedId) {
		$jdata = get_joined_record('travel_stay_table', $selectedId);
		if($jdata === false) $jdata = get_defaults('travel_stay_table');
		$rdata = $row;
	}
	$templateCode .= loadView('travel_stay_table-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: travel_stay_table_dv
	if(function_exists('travel_stay_table_dv')) {
		$args = [];
		travel_stay_table_dv(($hasSelectedId ? $selectedId : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}